### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by igordot** [jts/nanopolish#97] opened 2016-12-22 02:56 UTC
I ran nanopolish on several genomes and it seemed to work fine. However, I ran into trouble with one. The genome is about 5 MB and I have 200 MB of total reads. Those numbers seem to be in the reasonable range. When I compute the consensus sequence, most of the segments are processed fine, but there is one that consistently gets a `core dumped` error. The dump is over 300 GB, which seems excessive considering how much data I am processing. Do you know why this may be happening?

The only problem I can think of is that maybe that region has excessive coverage, but the coverage is fairly even and there are other ranges with a lot more reads.

**Comment by jts** [comment] 2016-12-22 03:53
HI,

I'll need a little more information to debug this. Could you try to open the core file in gdb and provide a backtrace?

Thanks,
Jared

**Comment by igordot** [comment] 2016-12-30 19:04
Sure. Do you know how I can retrieve that? I am not sure how to do that for a binary.

**Comment by igordot** [comment] 2017-01-24 17:37
I have a bit of a followup. I changed the window size in `nanopolish_makerange.py` from 50kb to 10kb.

**Comment by jts** [comment] 2017-01-26 01:04
Could you try to run nanopolish in gdb and send me the output? Here's some instructions:

```
gdb --args nanopolish variants --threads 2 --consensus polished.tig00000000:4730000-4740200.fa --window tig00000000:4730000-4740200 --min-candidate-frequency 0.1 --models nanopolish_models.fofn --reads reads.fa --genome draft.fa --bam reads.bam --outfile nanopolish-variants.txt --event-bam reads.eventalign.bam
```

when gdb starts type `r` and wait for it to run. When it segfaults type `bt` and copy and paste output into this issue. Thanks!

**Comment by igordot** [comment] 2017-01-26 01:47
Thank you for the clarification. Here is the output (including the part before `bt` for context).

```
registering model t.007-base
registering model t.007-ONT
[New Thread 0x2aaaabeac700 (LWP 28836)]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaaabeac700 (LWP 28836)]
0x000000301b4325e5 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000301b4325e5 in raise () from /lib64/libc.so.6
#1  0x000000301b433dc5 in abort () from /lib64/libc.so.6
#2  0x00002aaaaab5bb6d in __gnu_cxx::__verbose_terminate_handler() () at ../../.././../gcc-5.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00002aaaaab59bb6 in __cxxabiv1::__terminate(void (*)()) () at ../../.././../gcc-5.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00002aaaaab58c09 in __cxa_call_terminate () at ../../.././../gcc-5.2.0/libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00002aaaaab59555 in __gxx_personality_v0 () at ../../.././../gcc-5.2.0/libstdc++-v3/libsupc++/eh_personality.cc:676
#6  0x00002aaaab08be53 in _Unwind_RaiseException_Phase2 () from /local/apps/gcc/5.2.0/lib64/libgcc_s.so.1
#7  0x00002aaaab08c377 in _Unwind_Resume () from /local/apps/gcc/5.2.0/lib64/libgcc_s.so.1
#8  0x0000000000493a34 in float profile_hmm_fill_generic_r9<ProfileHMMForwardOutputR9>(HMMInputSequence const&, HMMInputData const&, unsigned int, unsigned int, ProfileHMMForwardOutputR9&) () at src/hmm/nanopolish_profile_hmm_r9.inl:267
#9  0x00000000004922f2 in profile_hmm_score_r9(HMMInputSequence const&, HMMInputData const&, unsigned int) () at src/hmm/nanopolish_profile_hmm_r9.cpp:53
#10 0x000000000049d847 in select_variant_set () at src/common/nanopolish_variant.cpp:175
#11 0x00002aaaaae6a01e in gomp_thread_start () at ../.././../gcc-5.2.0/libgomp/team.c:118
#12 0x000000301bc07aa1 in start_thread () from /lib64/libpthread.so.0
#13 0x000000301b4e8aad in clone () from /lib64/libc.so.6
```

**Comment by jts** [comment] 2017-01-26 01:57
Thanks, that is helpful. Would it be possible to narrow the region down further, and send me the associated fast5s and assembly? I'll probably need that to debug it further, since the crash is in the HMM calculation and its hard to see what the problem is.

**Comment by igordot** [comment] 2017-01-26 02:33
How small should I go? 1kb?

Is there a way to narrow down to the relevant fast5s or would I have to gather them all?

**Comment by jts** [comment] 2017-01-26 02:35
It is likely there is a single "bad" read that is causing the problem - if you could narrow it down to a 1kb region that would be great. 

It would be better if you can extract the relevant fast5s only. If you'd like I can write a script to do this (you'd give it the region and the bam file, it would package the fast5s) but it will take me a few days to get to it.

**Comment by igordot** [comment] 2017-01-26 02:43
Okay. I'll narrow it down more.

I don't know how to extract the relevant fast5s, so if you can write a script, that would be great.

**Comment by jts** [comment] 2017-01-26 02:44
Ok, I'll write the script then be in touch.

**Comment by igordot** [comment] 2017-02-28 02:38
I repeated with 1kb windows as you suggested. There is still only one window that crashes with a 360GB core dump. Let me know if you can still help me with finding the bad fast5.

**Comment by igordot** [comment] 2017-03-15 17:10
Just wanted to follow up regarding this issue in case it got lost in the shuffle.

**Comment by jts** [comment] 2017-03-15 17:42
Hi,

I haven't forgotten about this, I just haven't had time to work on it, sorry.

**Comment by igordot** [comment] 2017-03-15 17:46
No problem. Thank you for clarifying.

**Comment by jts** [comment] 2018-02-05 20:12
This is likely fixed by the many changes to input handling recently, please reopen if it reoccurs though.

**Closed by jts** 2018-02-05 20:12 UTC
Labels: bug
