### ISSUE TITLE
Tutorial on README seems wrong

### ISSUE THREAD

**Issue by conchoecia** [jts/nanopolish#429] opened 2018-08-02 18:55 UTC
I keep getting the error: `variants: too many arguments` when I follow the tutorial in the `README.md` about using parallel. 

For example:

```
        python {params.makerangescript} {input.fasta} | \
        parallel --results {params.results} -P 1 \
            nanopolish variants --consensus \
             -o {params.vcfs}.{{1}}.vcf \
             -w {{1}} \
             -r {input.reads} \
             -b {input.bam} \
             -g {input.fasta} \
             -t {threads} \
             --min-candidate-frequency 0.1
```

follows the `README.md`, but the help prompt now says this about `--consensus`: `--consensus=FILE                 run in consensus calling mode and write polished sequence to FILE`.

It seems like the command line usage has changed a little bit, and I was wondering if you could clarify the correct usage of nanopolish with `parallel`? Thank you!

**Comment by jts** [comment] 2018-08-02 19:10
Are you using the latest version (`0.10.1`)? You can check with `nanopolish --version`

**Comment by conchoecia** [comment] 2018-08-02 19:12
Nope! 0.9.1

**Comment by jts** [comment] 2018-08-02 19:16
Ok just upgrade and you should be set. Here's an explanation of the change:

https://github.com/jts/nanopolish#release-notes

**Comment by conchoecia** [comment] 2018-08-02 20:55
Ah - thank you. It seems like nanopolish won't create new directories for `-o` if they do not exist, correct? It might be good to add a warning if so. Right now I'm getting no output to stdout and no vcf files created. However, this isn't related to my original question. :^)

**Comment by jts** [comment] 2018-08-02 21:30
Correct it won't create the directory. Does it just silently fail?

**Comment by conchoecia** [comment] 2018-08-02 21:35
It just silently fails when I use it with `parallel`, and it seg faults when run by specifying the `-w` parameter.

**Comment by jts** [comment] 2018-08-02 21:39
Ok thanks, I'll add a warning.

**Comment by jts** [comment] 2018-08-02 21:46
Fixed in 1272e8e, thanks for reporting.

**Closed** 2018-08-10 20:30 UTC

**Comment by yjx1217** [comment] 2018-08-12 19:52
Hello,

I've encountered the same problem with nanopolish v0.10.1.  The command that I used is following:

python3 $nanopolish_dir/scripts/nanopolish_makerange.py $prefix.assembly.raw.fa | $parallel_dir/parallel --results nanopolish.results -P 8 \
        $nanopolish_dir/nanopolish variants --consensus $prefix.polished.{1}.vcf -w {1} --ploidy $ploidy -r $long_reads -b $prefix.minimap2.bam -g $prefix.assembly.raw.fa -t $threads
 
So could you help to figure out what might have caused this error?
In addition, there are several things that I'd like to double check:
1) The system that I worked with doesn't have parallel pre-installed, so I installed the version "parallel-20180722"  from http://ftp.gnu.org/gnu/parallel/. Is this correct?
2) What's the meaning of "-P 8" here  (suggested by the README file)? It doesn't seem like a parameter of parallel or nanopolish, so I got confused here.
3) By default, nanopolish has the setting of "--min-candidate-frequency 0.2", but the command example in the README file suggest to use "--min-candidate-frequency 0.1" . So which value would you recommend in general?

Thanks!

Best,
Jia-Xing

**Comment by jts** [comment] 2018-08-12 19:59
Hi,

The command should be:

```
python3 $nanopolish_dir/scripts/nanopolish_makerange.py $prefix.assembly.raw.fa | $parallel_dir/parallel --results nanopolish.results -P 8 
$nanopolish_dir/nanopolish variants --consensus -o $prefix.polished.{1}.vcf -w {1} --ploidy $ploidy -r $long_reads -b $prefix.minimap2.bam -g $prefix.assembly.raw.fa -t $threads
```

(note the `-o` after `--consensus`)

For your other questions:

1. Yes, that should be fine
2. `-P 8` means to polish 8 segments of the genome at once (the total number of threads used will be 8 x $threads)
3. This value does not have a big effect on the results. I suggest `0.2`.

Jared

**Comment by yjx1217** [comment] 2018-08-12 20:36
Got it! Many thanks for the quick reply and explanation!

Best,
Jia-Xing

**Comment by devonorourke** [comment] 2018-08-20 20:49
Hi Jared,

Hoping for a brief clarification regarding your last comment in this thread (where I put in a confused emoji): in the [release notes](https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly) for version 0.10.1 where you cover how to call variants while invoking the `parallel` program, the entirety of your code, though split into two chunks for readability, is effectively a one-liner.

However, in [this thread](https://github.com/jts/nanopolish/issues/429), you've split the code into two definitive lines:
```
python3 $nanopolish_dir/scripts/nanopolish_makerange.py $prefix.assembly.raw.fa | $parallel_dir/parallel --results nanopolish.results -P 8 
$nanopolish_dir/nanopolish variants --consensus -o $prefix.polished.{1}.vcf -w {1} --ploidy $ploidy -r $long_reads -b $prefix.minimap2.bam -g $prefix.assembly.raw.fa -t $threads
```

I had been following this thread initially to try to understand exactly how to work with a genome with many scaffolds and kept getting mistakes where a new folder would be created and named for each unique scaffold window (instead of a new `.vcf` file). After plugging in the `\` to the command listed in this thread (matching what is currently in the release notes) things worked as expected.

So if anyone is wondering why the command above didn't work, perhaps it's because they were searching in your repo, came across this thread, and didn't notice (like I did!) that your suggested command was intended to always be a one-liner.

Thanks

**Comment by jts** [comment] 2018-08-20 20:58
Hi Devin,

That thread links back here - could you fix the link so I can see what you're referring to?

In any case that should always be a one-liner.

Jared

**Comment by devonorourke** [comment] 2018-08-20 21:03
Yep;
It's this thread we're chatting in. Look to your comment listed as **8 days ago** . Or, within this thread, search for the confused emoji 😕

**Comment by jts** [comment] 2018-08-20 21:05
Oh sorry. I fixed the command, sorry for the confusion.
