### ISSUE TITLE
nanopolish extract all only produces 2d

### ISSUE THREAD

**Issue by dmacmillan** [jts/nanopolish#116] opened 2017-02-22 21:33 UTC
I found that when I use the `nanopolish extract` command with the `-t all` flag I only end up with a single sequence, which is the 2d sequence. I must specify `-t template` and `-t complement` separately to yield the other two sequences. I do not know if this behavior is intentional or not but I expected `-t all` to yield all 3 sequences.

**Comment by jts** [comment] 2017-02-22 21:35
@mateidavid is this expected behaviour?

**Comment by mateidavid** [comment] 2017-02-23 03:00
Currently this is the intended behaviour. The option only affects which basecall groups get searched, but no matter what gets searched, only the first hit is used from a given file. Here, "hit" means basecall group name and read type (template/complement/2d) that has fastq and event-level data. Perhaps I should rename the option to `any` instead of `all`?

Is there a good reason for `nanopolish extract` to extract multiple fastq entries from the same file? I mean, as opposed to using `f5dump` from `fast5`, or `poretools`, or other tools?

**Comment by jts** [comment] 2017-03-11 20:19
I think the current behaviour should be kept (only output one sequence per fast5) but the option should be renamed. `any` seems good to me.

**Comment by jts** [comment] 2017-03-16 15:34
Fixed in 0.6.

**Closed by jts** 2017-03-16 15:34 UTC
