### ISSUE TITLE
AssertionError when running nanopolish_merge.py

### ISSUE THREAD

**Issue by dikkeaap** [jts/nanopolish#199] opened 2017-07-31 16:31 UTC
Hi,

I'm getting the following error when running nanopolish_merge.py on an assembly generated by Canu:

> Traceback (most recent call last):
>   File "/home/eda/tools/nanopolish-20170717/scripts/nanopolish_merge.py", line 89, in <module>
>     assert(prev_segment is None or prev_segment + SEGMENT_LENGTH + OVERLAP_LENGTH > segment_start)
> AssertionError

I ran nanopolish through the nanopolish_makerange.py script. There are two chunks that did not produce an output fasta file:

> tig00001595:50000-100200
> tig00002641:100000-100034

I tried to rerun these specific chunks but they both give the same error:

> nanopolish: src/alignment/nanopolish_alignment_db.cpp:364: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed.

I'm assuming these are two unrelated problems. The stderr file for the first one (tig00001595) shows:

> nanopolish: src/nanopolish_haplotype.cpp:103: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.

The stderr for the second one (tog00002641) shows:

> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc

I'm guessing the second one is related to the small size of the chunk; but for the first one, I can't see anything peculiar about it.

**Comment by BertVanm** [comment] 2017-08-14 09:12
I seem to be getting the same error

> nanopolish: src/alignment/nanopolish_alignment_db.cpp:364: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed

I wonder if it's due to the absence of reads mapping to a certain region

**Comment by jts** [comment] 2017-08-17 13:10
Hi,

Thanks for the report. Would either of you be able to make a small test data set that reproduces the problem so I can try to track it down and fix it?

Jared

**Comment by dikkeaap** [comment] 2017-08-21 08:49
Hi Jared,

for the first error (tig00001595:50000-100200) I have created a dataset where the genome fasta consists only of the exact region of the contig; the reads fasta + bam files contain only all reads that map to the contig. This dataset fails to reproduce the error; it goes through fine. 

I can only reproduce the error by using the full genome fasta file and specifying the window, with the aformentioned reads fasta + bam file. I can provide this dataset to you through ftp, please contact me for details. Also let me know if you *require* the fast5 files, as it will be a bit of effort to collect the appropriate ones.

The second error (tig00002641:100000-100034) is most likely a different bug, just look at the window size - it's smaller than 40 bp.

**Comment by jts** [comment] 2017-08-29 13:31
Hi @dikkeaap,

I tried polishing a 40bp window on a local genome and it worked without error. I think I'll need your dataset, including the fast5s. Sorry for the hassle.

Jared

**Comment by alexandervogel** [comment] 2017-09-05 11:55
Hi,
I stumbled across a similar issue giving the same error message as described above. Checking the output of the nanopolish_makerange.py run I assume it could be related to contigs where the overlap is larger than the actual end of the contig?

`Consensus_utg4130:0-50200
Consensus_utg4130:50000-100200
Consensus_utg4130:100000-100130`

**Comment by jts** [comment] 2017-09-05 13:18
Hi @alexandervogel,

Were the contigs you listed above successfully created by `nanopolish variants` - is this only a failure at the `nanopolish_merge` step?

**Comment by alexandervogel** [comment] 2017-09-05 13:38
Hi @jts ,

No, the corresponding task of nanopolish variants also died with the following error message:

> nanopolish: src/nanopolish_haplotype.cpp:103: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.

I saw this error message in another issue here, but as it is currently under investigation decided to fill the missing segment with the unpolished sequence for now until the subsequent error occurred. For now, I will just exclude the entire corresponding contig (plus another one). Which allowed me to run the merge successfully.

**Comment by jts** [comment] 2017-09-05 13:39
Ok, thanks for letting me know. I'm preparing a major new release to address albacore 2.0 compatibility, I'll come back to this issue after I post the new code.

**Comment by jts** [comment] 2017-09-06 15:28
Hi @dikkeaap, @BertVanm, @alexandervogel,

I've just improved the error message when this situation occurs:

```
nanopolish: src/alignment/nanopolish_alignment_db.cpp:364: void AlignmentDB::load_region(const string&, int, int): Assertion `m_region_end >= 0' failed.
```

Could you please re-run the latest code of nanopolish on the segments that failed and update me on what error your receive?

Thanks

**Comment by dikkeaap** [comment] 2017-09-07 11:40
I just checked out the latest code from git and built it.

When I run

chunk="tig00001595:50000-100200"
/home/eda/tools/nanopolish-20170907/nanopolish variants --consensus polished.${chunk}.fasta -w ${chunk} -r reads.fasta -b reads.sorted.bam -g reference.fasta -t 4 --min-candidate-frequency 0.1

I am getting 

[fai_load] build FASTA index.
[fai_build] fail to open the FASTA file reads.fasta.fa.gz
[fai_load] fail to open FASTA index.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140246245296128:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  : : error in H5Fopen
Aborted (core dumped)

As you can see, nanopolish tries to build an index from a file that doesn't exist (it appends .fa.gz to the reads.fasta file name). I can make the fai error 'go away' by (1) manually running "samtools faidx reads.fasta"; and (2) symlinking reads.fasta.fa.gz -> reads.fasta, and reads.fasta.fa.gz.fai -> reads.fasta.fai . But the HDF5 error remains. I also tried this version of nanopolish on a 'good' contig, as well as on another (completely unrelated) dataset but with the same result, so I think something is broken with the newest version.

**Comment by dikkeaap** [comment] 2017-09-07 13:36
I just checked out the latest code from git and built it.

When I run

chunk="tig00001595:50000-100200"
/home/eda/tools/nanopolish-20170907/nanopolish variants --consensus polished.${chunk}.fasta -w ${chunk} -r reads.fasta -b reads.sorted.bam -g reference.fasta -t 4 --min-candidate-frequency 0.1

I am getting 

[fai_load] build FASTA index.
[fai_build] fail to open the FASTA file reads.fasta.fa.gz
[fai_load] fail to open FASTA index.
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140246245296128:
  #000: H5F.c line 591 in H5Fopen(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  : : error in H5Fopen
Aborted (core dumped)

As you can see, nanopolish tries to build an index from a file that doesn't exist (it appends .fa.gz to the reads.fasta file name). I can make the fai error 'go away' by (1) manually running "samtools faidx reads.fasta"; and (2) symlinking reads.fasta.fa.gz -> reads.fasta, and reads.fasta.fa.gz.fai -> reads.fasta.fai . But the HDF5 error remains. I also tried this version of nanopolish on a 'good' contig, as well as on another (completely unrelated) dataset but with the same result, so I think something is broken with the newest version.

**Comment by jts** [comment] 2017-09-07 13:46
Hi @dikkeaap, 

Did you see my message above?

**Comment by dikkeaap** [comment] 2017-09-07 13:54
I fixed the indexing issue by running "nanopolish index reads.fasta" (as per Jared's email response). 

When I now run

chunk="tig00001595:50000-100200"
/home/eda/tools/nanopolish-20170907/nanopolish variants --consensus polished.${chunk}.fasta -w ${chunk} -r reads.fasta -b reads.sorted.bam -g reference.fasta -t 4 --min-candidate-frequency 0.1

I get

nanopolish: src/nanopolish_haplotype.cpp:103: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.

**Comment by jts** [comment] 2017-09-08 13:50
I've fixed the second issue - you are right it is caused by a short window at the end of the contig. I now disallow such windows and rewrote `nanopolish_makerange.py` so it includes the contig ends with the previous segment if it is less than 1000bp.

I still don't know the cause of the first issue. Could you re-run it with debug info turned on (`-vvvvvvvv`) and send me the output?

**Comment by jts** [comment] 2017-09-08 13:56
Actually, I'm going to add some debug code to help track down this bug, hang on before you re-run it.

**Comment by jts** [comment] 2017-09-08 14:07
Debug info added, please update to the latest (33add05) and send me the output

**Comment by dikkeaap** [comment] 2017-09-11 08:36
Hi Jared, I just cloned the latest code and ran it on the erroneous chunk with -vvvvvvv and collected the stdout / stderr messages. Because the data is privately owned (and the output contains the sequence) I can only share it with you - could you please provide with with an email address I can send it to ?

**Comment by jts** [comment] 2017-09-11 14:08
jared.simpson@oicr.on.ca - thanks!

**Comment by jts** [comment] 2017-09-12 18:20
With the help of the log files you provided I've identified a possible issue. Could you try the very latest code (including commit `a35b05f`) to see if the problem still occurs?

**Comment by dikkeaap** [comment] 2017-09-14 10:52
I cloned the latest code this morning, unfortunately the issue still persists:

> nanopolish: src/nanopolish_haplotype.cpp:113: Haplotype Haplotype::substr_by_reference(size_t, size_t) const: Assertion `derived_base_end != m_coordinate_map.size()' failed.

I have mailed you the stdout / stderr output of the attempt. Any help would be appreciated!

**Comment by apredeus** [comment] 2017-10-28 10:40
I've got the same error on a couple of fragments with v.0.8.1 on a Canu assembly. Nothing like this happened on two other (miniasm) assemblies. Seems like it's something specific to Canu? (Judging from the contig names, OP's assembly is also from Canu)

**Comment by dikkeaap** [comment] 2017-10-30 09:13
I'm running into the same issue again with another (Canu) assembly. The workaround I have applied until now is to run the problematic contig through nanopolish as a whole, rather than chunking it. This takes rather long (depending on the contig size of course) but has helped me circumvent the issue thusfar.

**Comment by jts** [comment] 2017-10-30 14:30
Hi,

Sorry I haven't been able to fix this yet as I can't reproduce it locally. I'll ask again if you could isolate a test case (eg. only the fast5 files for the chunk that causes the error and the full assembly sequence) so I can debug it here. Any help would be appreciated.

Jared

**Comment by pwkooij** [comment] 2017-11-29 13:27
Is there any update on this issue? I am having the same problem

**Comment by jts** [comment] 2017-12-05 15:20
Hi all,

We now have a way to debug this issue. @jopineda wrote a script that will extract all of the information we need to locally reproduce this error. You'll need to run the following three steps:

1. Narrow down the region that makes nanopolish crash by running `nanopolish variants --consensus [...]` and changing the `-w` parameter.
2. Once you have a small region that always causes nanopolish to crash, run this program that is found in the `scripts` directory of nanopolish:
```
python extract_reads_aligned_to_region.py -b reads.sorted.bam -r reads.fastq -g draft.fa -w "contig:start-end"
```
(you'll have to replace `reads.fastq`, `reads.sorted.bam` and `draft.fa` with the names of the files you generated, and replace `contig:start-end` with the name of the contig you are polishing and the `start`/`end` coordinates of the region that crashes nanopolish.
3. The extraction script will take a little while to run and produce a `.tar.gz` file. Please send us this file by hosting on dropbox or google drive and we'll fix the problem.

Thanks!
Jared

**Comment by pwkooij** [comment] 2017-12-06 10:37
Hi Jared

For the extract script I receive the following error:

`Traceback (most recent call last):
  File "/var/lib/nanopolish/scripts/extract_reads_aligned_to_region.py", line 17, in <module>
    custom_print(('Missing package(s)'))
NameError: name 'custom_print' is not defined
`

Any suggestion?

Cheers
Pepijn

**Comment by jts** [comment] 2017-12-06 13:37
Hi @pwkooij,

Can you confirm you are using the very latest version of nanopolish from github?

Thanks,
Jared

**Comment by pwkooij** [comment] 2017-12-06 14:28
I currently have version 0.8.4, is that the latest one?
I also have the manager of the cluster checking some of the other programs it is trying to import

Cheers
Pepijn

**Comment by pwkooij** [comment] 2017-12-07 14:49
Hi Jared

Pysam was the issue for the error above. That is fixed now, but now I get the following error:

`usage: extract_reads_aligned_to_region.py [-h] [-v] -b BAM [-f FA_FILENAME] -g
                                          DRAFT_GA -c DRAFT_GA_COORDS -r
                                          READDB [-o OUTPUT_PREFIX]
extract_reads_aligned_to_region.py: error: argument -c/--draft_ga_coords is required`

Any ideas for this one?

Cheers
Pepijn

**Comment by jts** [comment] 2017-12-07 15:24
Hi @pwkooij,

It still looks like the script is out of date, could you update to the latest please? You should follow the instructions here to update:

https://github.com/jts/nanopolish#installing-the-latest-code-from-github-recommended

When you have the latest version the instructions here should help:

http://nanopolish.readthedocs.io/en/latest/debug.html

Jared

**Comment by pwkooij** [comment] 2017-12-08 16:00
Hi Jared

We managed to get it to work. You can find the files for both datasets [here](https://drive.google.com/open?id=1U3P_txxtcTh1HeT76v23D-X9ObTzOxTh)

Please let me know if you need anything else.

Cheers
Pepijn

**Comment by jts** [comment] 2017-12-08 20:59
Thank you, I've identified the problem and should have a fix soon.

**Comment by jts** [comment] 2017-12-08 21:44
I have a fix but I need to test it over the weekend. I'll push the new code on Monday

**Comment by pwkooij** [comment] 2017-12-09 11:02
Hi Jared,

That's great news. Could you give any details as to what the problem was?

Cheers
Pepijn

**Comment by jts** [comment] 2017-12-11 14:58
Hi @pwkooij,

My tests passed so I've updated github with the new code. The version tagged as `0.8.5` should work for you.

The problem was caused by a very long read (~500kb) that was made up mostly of short repeats (`TAA` over and over). When nanopolish parsed this read it could not make a reliable alignment between the events and the basecalled sequence. This lead to a problem later when it looked up the events for a particular base, as it found no events nearby which triggered the assertion. To fix this I added a new check to make sure the event-to-base alignment does not have large gaps.

I'm going to close issue #265, please let me know if you have more problems.

Jared

**Comment by pwkooij** [comment] 2017-12-11 15:02
Thanks! Do I have to index the data again, or can I just run the `nanopolist variants` for the previously problematic contig?

**Comment by jts** [comment] 2017-12-11 15:03
If you update the code you should be able to just run `nanopolish variants`.

**Comment by jts** [comment] 2018-01-05 20:59
Commit e490d23 fixes the long-standing `derived_base_end != m_coordinate_map.size()` error so this issue is finally resolved.

**Closed by jts** 2018-01-05 20:59 UTC
