### ISSUE TITLE
Error running (newest) nanopolish

### ISSUE THREAD

**Issue by rmnorris** [jts/nanopolish#23] opened 2015-10-23 09:18 UTC
Using the current commit of nanopolish on a bacterial PBcR assembly, I got this error from the nanopolish consensus step:

> nanopolish: src/nanopolish_consensus.cpp:674: void train_segment(HMMRealignmentInput&, uint32_t): Assertion `!input.empty()' failed.

But only for two of the ranges created by nanopolish_makerange.py out of 60. What is missing? Is this a data problem?

**Comment by jts** [comment] 2015-10-23 13:05
I think what is happening is that a segment of your genome is not covered by 2D reads. This probably shouldn't be an assertion. I'll make a quick change.

**Comment by jts** [comment] 2015-10-23 13:29
I've just made the change in d0e86c4, can you try it and let me know if the problem is fixed?

**Comment by rmnorris** [comment] 2015-10-23 14:31
Thanks! I just gave it a go, just on the two segments which threw errors last time. I don't get an error any more from the consensus step, but it is skipping the problematic ranges (and has overwritten the scf7180000000039 40-48 which were not problematic but 49 was and the region was 40-50) and so the merge step has this error:
> ERROR_MISSING scf7180000000039 40
>...
> ERROR_MISSING scf7180000000039 49
> ERROR_MISSING scf7180000000042 0
> ...
> ERROR_MISSING scf7180000000042 9
Also, the PBcR assembly is reference free - my draft assembly is created from the 2d reads only. I'm not sure how it is possible to create a draft genome with areas not covered by 2d reads from 2d reads. Maybe it's a PBcR thing?

**Comment by jts** [comment] 2015-10-23 15:06
I'm a bit confused by that as the original sequence should be output even if there are no reads:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_consensus.cpp#L709

Could you run consensus on a single segment in verbose mode (add the option "-vvvvv") and sent me the output by email?

**Comment by jts** [comment] 2015-11-03 21:23
Fixed in 3bb2c69306

**Closed by jts** 2015-11-03 21:23 UTC
