### ISSUE TITLE
'Non type' error with methylation frequency calculation

### ISSUE THREAD

**Issue by qtran1** [jts/nanopolish#671] opened 2019-10-16 21:24 UTC
Hi, 
I run the calculate_methyaltion_frequency.py and got this below error. Do you have any suggestions? I checked my 'num_motifs' column and did not see any suspected problem. 

[qtran@splprhpc05 workspace]$ /scripts/calculate_methylation_frequency.py methyl_chr17_cpg.tsv > methyl_chr17_freq.tsv
Traceback (most recent call last):
  File "/home/qtran/bin/nanopolish/scripts/calculate_methylation_frequency.py", line 41, in <module>
    num_sites = int(record['num_motifs'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by mattingsdal** [comment] 2019-10-16 21:29
I just googled "int() argument must be a string, a bytes-like object or a number, not 'NoneType'" and also get this. 

I got this error after generating calls with:

"nanopolish call-methylation -t 8 -r file.fastq -b file.bam -g genome.fa -q cpg >file.tsv"
"calculate_methylation_frequency.py file.tsv >file.freq.tsv

the file.tsv is 6 GB

**Comment by jts** [comment] 2019-10-16 21:37
Hi,

Just so I'm clear both of you (@qtran1 and @mattingsdal) have the same error, on different datasets? 

The error message probably means the input file (if its not empty) is corrupt somehow. Can you send me the file (or a small part of it that reproduces the error).

thanks
Jared

**Comment by qtran1** [comment] 2019-10-16 21:45
I sent you the input file.

**Comment by jts** [comment] 2019-10-16 21:55
Thanks! It looks like stderr was redirected to stdout, which results in a corrupt line (note the "post-run summary" part):

```
chr17   +       9239896 9239920 e523e653-05e1-4986-a89a-ccddc46f4ae6    23.02   -321.43 -344.45 1       6       AGTGGCGGGACACGTGGGCGCGGCGGCTGCGCAAG
chr17   +       9239935 9239935 e523e653-05e1-4986-a89a-ccddc46f4ae6    [post-run summary] total reads: 1263, unparseable: 0, qc fail: 0, could not calibrate: 39, no alignment: 27, bad fast5: 0
4.00    -160.84 -164.84 1       1       AGCAGCGTGAG
```

I'm not sure how this can happen - @qtran1, how did you run `call-methylation`? 

@mattingsdal can you check to see if you see the same issue in your file?

**Comment by mattingsdal** [comment] 2019-10-16 22:34
Yes.. there is corrupted line, caused by failed QC of a read ? 

I'm including three lines

gi|924926445|ref|NW_012412206.1|	+	1075	1075	64cf51a3-38a7[post-run	summary]	total	reads:	2415112,	unparseable:	0,	qc	fail:	4159,	could	not	calibrate:	30460,	no	alignment:	42723,	bad	fast5:	0

-41c2-a05a-35a74b6c8b00	0.29	-163.55	-163.85	1	1	CACCCCGTTTA

gi|924926445|ref|NW_012412206.1|	+	1128	1128	64cf51a3-38a7-41c2-a05a-35a74b6c8b00	4.61	-110.82	-115.43	1	1	CCATTCGGTAG




>

**Comment by qtran1** [comment] 2019-10-16 23:00
This is how I run the methylation call
`bsub -P Nanopore -J methylationCall -q standard -R 'rusage[mem=64000]' -o /fast5_pass2/workspace/methylation_calls_chr17.tsv nanopolish call-methylation -t 1 --methylation cpg -r /fast5_pass2/workspace/all_reads.fastq -b /fast5_pass2/workspace/all_reads.sorted.bam -g /home/qtran/ref_genomes/hg38.fa -w "chr17:5000000-10000000" `

**Comment by jts** [comment] 2019-10-16 23:09
I think your cluster might be configured to redirect stderr to stdout and this causes the issue, is this possible?

**Comment by qtran1** [comment] 2019-10-16 23:11
Could be! I can rerun with the option -e to make sure it will send the error to a file. Even that, I don't know what happened in my case, these are all passed QC reads (qc failed: 0 and bad fast5: 0) unlike what @mattingsdal has. Let me rerun the command and update.

**Comment by jts** [comment] 2019-10-16 23:22
The 'post-run' message is always printed, its just an end-of-run status message.

**Comment by mattingsdal** [comment] 2019-10-17 09:33
So I will try 1>STOUT 2>STERR let you know how it goes

nanopolish call-methylation -t 8 -r file.fastq -b file.bam -g genome.fa -q cpg 1>file_cpg.STOUT.tsv 2>file_cpg.STERR.tsv

**Comment by mattingsdal** [comment] 2019-10-17 22:24
> So I will try 1>STOUT 2>STERR let you know how it goes
> 
> nanopolish call-methylation -t 8 -r file.fastq -b file.bam -g genome.fa -q cpg 1>file_cpg.STOUT.tsv 2>file_cpg.STERR.tsv

update: yes.. 1>STOUT and 2>STERR solved my issue.. thanks

**Comment by jts** [comment] 2019-10-17 22:52
Great, thanks for the update.

**Comment by vahidAK** [comment] 2019-10-17 23:31
Hi @jts ,
I also faced this problem but solve it by this code:
awk -F'\t' ' $10>=1 { print $0 }' OFS='\t' methylation_calls.tsv > methylation_calls_removedNON.tsv
and then I did methylation freq script.
Does it right way to do this?
Thanks,
Vahid.

**Comment by qtran1** [comment] 2019-10-18 19:49
> Could be! I can rerun with the option -e to make sure it will send the error to a file. 

Update: The -e option works for me. 1> and 2> did not work.

**Comment by vahidAK** [comment] 2019-10-19 00:30
Hi @qtran1 ,
Try this:  
awk -F'\t' ' $10>=1 { print $0 }' OFS='\t' methylation_calls.tsv > methylation_calls_removedNON.tsv  
It worked for me.
There must be only a non type line in the file with you can remove it by the above code.

**Comment by jts** [comment] 2019-10-21 13:42
Thanks @vahidAK for that suggestion. It is better in general though to fix the commands (or the cluster submission script) to make sure stderr is not redirected to stdout. Since that appears to be the root cause of this issue I'll now close it.

**Closed by jts** 2019-10-21 13:42 UTC
