### ISSUE TITLE
Does sequencing summary file created by Guppy could work for nanopolish index ?

### ISSUE THREAD

**Issue by DAVID2022** [jts/nanopolish#569] opened 2019-03-29 02:04 UTC
Hi ,
So sequencing summary file created by any base calling software can be used to accelate the process of nanopolish index ? Whatever it is Albacore, Guppy, or Flappie？Is there any requirement for the sequencing summary file that put into nanopolish index?
Best wishes,
David

**Comment by jts** [comment] 2019-03-29 13:47
Closing as this is a duplicate of a comment made in a different issue.

Jared

**Closed by jts** 2019-03-29 13:47 UTC

**Comment by DAVID2022** [comment] 2019-03-30 03:29
Thank you very much for your help! 
Best wishes,
David.
