### ISSUE TITLE
Nanopolishing taking a long time to compute consensus sequence

### ISSUE THREAD

**Issue by jotes35** [jts/nanopolish#854] opened 2020-11-05 14:08 UTC
I have  5.6MB Draft Asssemby which I am polishing with nanopolish. The script has been running for over 24 hours and  is still running. Is it normal for nanopolish to take that long? or there is something I am doing wrong.  Below is the code which is taking long to run

_python3 nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
    nanopolish variants --consensus -o polished.{1}.vcf -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1_

**Comment by jts** [comment] 2020-11-05 14:20
Closing as duplicate of #855

**Closed by jts** 2020-11-05 14:20 UTC
