### ISSUE TITLE
bad fast5

### ISSUE THREAD

**Issue by maguileraf** [jts/nanopolish#678] opened 2019-10-25 13:43 UTC
Hello,

When I try to use nanopolish_makerange.py I get the following error:
[post-run summary] total reads: 588, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 584

**Comment by jts** [comment] 2019-10-25 13:44
Hi @maguileraf,

This usually means something has gone wrong with the `nanopolish index` step, so it is unable to find the fast5 files for your reads. What messages did `nanopolish index` print?

Jared

**Comment by maguileraf** [comment] 2019-10-25 14:01
Hi Jared,

Thank you for your quick response. I get this: [readdb] num reads: 848174, num reads with path to fast5: 772883. I am following the Quickstart guide but I do not get any of the files that are stated in there.

**Comment by jts** [comment] 2019-10-25 14:05
So you don't see a `.readdb` file after `index`?

**Comment by maguileraf** [comment] 2019-10-25 14:05
Correct. I do not see any output files after index.

**Comment by jts** [comment] 2019-10-25 14:07
Ok, that must be the problem them. Can you paste here the full `nanopolish index` command that you ran?

**Comment by maguileraf** [comment] 2019-10-25 14:15
nanopolish index -d path_to_fast5_dir guppy_output_fastq. I do not have the summary.txt file.

**Comment by jts** [comment] 2019-10-25 14:20
Hm. The output above (`[readdb]...`) suggests the command ran successfully so I don't know why the files aren't there. Do you see files with the prefix `guppy_output_fastq.`?

**Comment by maguileraf** [comment] 2019-10-25 14:21
I do not see any files at all after the index is done. I was using the conda version, so I am going to clone it from here and install it and see if this works.

**Comment by maguileraf** [comment] 2019-10-28 20:14
It did not fix it :(

**Comment by jts** [comment] 2019-10-28 20:20
Can you try the tutorial dataset? https://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html

**Comment by maguileraf** [comment] 2019-10-28 21:13
It works with the tutorial dataset

**Comment by maguileraf** [comment] 2019-10-29 01:17
I found the files. They get created where my fastq files are instead of the directory where I was running nanopolish from. Thank you

**Comment by maguileraf** [comment] 2019-10-29 11:54
I found the files but still gives me the same thing [post-run summary] total reads: 479, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 479

**Comment by jts** [comment] 2019-10-29 13:19
Hi @maguileraf,

Can you confirm the fast5 files are readable from your current working directory? Can you run this command:

```
head -10 /path/to/guppy_output_fastq.index.readdb
```

This will print a list of read IDs (first column) and fast5 files (second column). Can you run `ls -l <fast5path>` on a few of the fast5s listed in the second column and paste the result?

Thanks

**Comment by maguileraf** [comment] 2019-10-29 14:24
-rw-rw-r-- 1 songli Intro2GDS 31039 Sep  6  2018 /groups/Intro2GDS/NanoporeTomato2019/20180905_2201_tomato_arec/fast5/pass/89/SP_SONGLI_XPS1_20180905_FAK11984_MN27847_sequencing_run_tomato_arec_33597_read_25127_ch_238_strand.fast5

**Comment by jts** [comment] 2019-10-30 19:44
I think I'll need a subset of your data to debug this problem further. Can you send me one fast5 file, and the corresponding fastq file, and instructions for reproducing the problem locally?

**Comment by jts** [comment] 2019-11-06 14:22
I'm closing this for now, if you can provide me with a fast5 file I'll be happy to help you debug further.

**Closed by jts** 2019-11-06 14:22 UTC

**Comment by glf20** [comment] 2020-03-13 17:33
Hi,
I have a similar issue as above and am getting same messsage.  Was there a solution on this?
Command used was: nanopolish variants --consensus -o polished_O.vcf -r filtered.fq -b polished.bam -g all__final.fa --min-candidate-frequency 0.1 -t 48

**Comment by jts** [comment] 2020-03-13 18:31
Hi,

Which version of nanopolish are you using?

Jared

**Comment by glf20** [comment] 2020-03-13 22:03
Hi,
Nanopolish, v0.12


Graham

**Comment by jts** [comment] 2020-03-13 22:20
Can you post any output messages from nanopolish index and nanopolish variants?

**Comment by glf20** [comment] 2020-03-14 07:33
Hi, 
Nanopolish, v0.12 

Graham

**Comment by szsctt** [comment] 2021-06-01 06:56
I have the same issue when trying to use `nanopolish call-methylation`, with nanopolish version 0.13.2.  The issue only occurs with one particular sample - the example data from the tutorial and my other samples all ran as expected. The command I'm using is:
```
nanopolish call-methylation -t 10 -q cpg -r out/reads/OTC3.fastq -b out/aln_region/OTC3.bam -g references/GRCh38.primary_assembly.genome.fa
```
I get the output:
```
[post-run summary] total reads: 298683, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 301710
```

An output file with a header (but nothing else) is created.

Before running this command, I indexed the fast5 files with the command:
```
nanopolish index -s out/reads/OTC3.sequencing_summary.txt -d out/reads/OTC3_fast5 out/reads/OTC3.fastq
```

Which gave the output:
```
[readdb] indexing out/reads/OTC3_fast5
[readdb] num reads: 17567172, num reads with path to fast5: 11370322
```

The files:
```
out/reads/OTC3.fastq.index.fai  
out/reads/OTC3.fastq.index.readdb
out/reads/OTC3.fastq.index  
out/reads/OTC3.fastq.index.gzi
```
Were created, and the top of the readdb file looks like this:
```
0000002c-5b28-4012-a91f-ae8a67fe5221	
000000d2-9ca5-434e-90ef-d9f734d4f4ab	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_932.fast5
0000011e-99ab-40ef-8b1d-0685a3a9b99b	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_1227.fast5
0000017a-ac2c-4dd1-8635-d4a8d0a62478	
000001a9-3566-4dcc-981c-73acb5983baa	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_1897.fast5
00000271-c1d4-4b90-ab67-b7b6265ddd66	
00000392-7a5c-480a-9a6a-ebd9fbb29d9d	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_1553.fast5
000003ea-3523-47c8-a51d-fd3741393be5	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_90.fast5
000003ed-c070-458d-af1e-50a7a0a293bf	out/reads/OTC3_fast5/PAG34515_pass_19bc49ff_822.fast5
0000045d-c822-443b-b1ea-cc566690c26e	
```

Not sure if those missing paths are a problem?  Anyway, the ones that are there do exist (although they are symlinks, not sure if that's a problem or not either).

I also tried running the index command without the `-s` argument, but I ran into the same issue (empty output file).

**Comment by szsctt** [comment] 2021-06-09 04:20
I figured this one out - user error (I was using the wrong folder when I built the index)

**Comment by manburst** [comment] 2021-11-06 13:57
Hello
I got the same problem but I have .readdb file (inside it I found the read name correlate to fast5 file) and I have checked that path that I used is correct.
This is the first time that I got this problem.
Version used 0.11.3

**Comment by manburst** [comment] 2021-11-06 14:22
Hello I got a similar issue
In my case, those reads are not bad_fast5 but it is "could not calibrate" and I look into the result tsv file those reads represent as read_fail_loaded but I have check-in readdb file that those reads exist.
