### ISSUE TITLE
error: could not parse model string:

### ISSUE THREAD

**Issue by devindrown** [jts/nanopolish#190] opened 2017-07-17 21:32 UTC
Running nanopolish version 0.7.1

After assembly with canu, I'm trying to run nanopolish on a dataset, but I keep getting the error: **could not parse model string:**

I'm working with Albacore basecalled 2D data I ran on a r9.4 flow cell. I used nanopolish to extract the fastq/fasta reads. I looked at the fast5 files and I noticed that the the models are:

UniqueGlobalKey:context_tags:
        local_bc_comp_model = complement_r9.4_250bps_5mer
        local_bc_temp_model = template_r9.4_250bps_5mer

Do I need to import new models for nanopolish to use? I noticed there are r9 250bps 5mer models, but not for r9.4. Just a guess on my part.

**INPUT command:**
```
 python ~/nanopolish/scripts/nanopolish_makerange.py draft.fa | parallel --results nanopolish.results -P 8 \
> nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -t 4 --min-candidate-frequency 0.1
```

**Full output:**
```
##fileformat=VCFv4.2
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
[fai_load] build FASTA index.
error: could not parse model string:
```

**Comment by jts** [comment] 2017-07-18 01:35
The keys `local_bc_temp_model` would suggest that you used MinKNOW local basecalling, not standalone albacore. If you use standalone albacore could you let me know what version you used?

**Comment by devindrown** [comment] 2017-07-18 02:03
I used Albacore 1.1.0
```
Basecall_2D_000 (769123, 2)
    Group size = 3
    Number of attributes = 6
        basecall_1d = Basecall_1D_001
        component = basecall_2d
        name = ONT Albacore Sequencing Software
        segmentation = Segmentation_001
        time_stamp = 2017-May-12 09:36:12
        version = 1.1.0
```
The original 2D run was "live" basecalled with MinKNOW, but that version (1.43) didn't produce a 2D consensus (only the template and compliment). As a result the fast5 hierarchy has multiple basecalls in it:

Basecall_1D_000 = MinKNOW
Basecall_1D_001 = Albacore
Basecall_2D_000 = Albacore

**Comment by jts** [comment] 2017-07-18 02:21
Since there are multiple basecalls in the file, when running `nanopolish extract` you have to explicitly tell it to extract the albacore basecalls: `nanopolish extract -b albacore`

**Comment by devindrown** [comment] 2017-07-18 03:06
I did use that option, see below

`nanopolish extract -r -b albacore -t 2d-or-template -o  output.fasta  /inputDIR`

**Comment by jts** [comment] 2017-07-18 03:24
Could you try with the latest albacore (1.2.5) and if the problem still exists, send me an example fast5?

**Comment by devindrown** [comment] 2017-07-18 04:17
I've been avoiding upgrading to the latest albacore because of the lack of 2D basecalling support. I suppose there is trick to keeping the configuration files while upgrading that I have to figure out. 

I've attached an example fast5 file in the mean time.
[stuart_20170316_FNFAF16106_MN20458_sequencing_run_AntiRes_MD_20170316_55189_ch101_read13147_strand.zip](https://github.com/jts/nanopolish/files/1154647/stuart_20170316_FNFAF16106_MN20458_sequencing_run_AntiRes_MD_20170316_55189_ch101_read13147_strand.zip)

**Comment by jts** [comment] 2017-07-18 14:20
Could you use albacore 1.2.4? It includes 2D support and should write fast5 in the format nanopolish expects.

**Comment by cjfields** [comment] 2017-07-19 15:33
@jts We're seeing the same problem in #194 .  We've been using the latest albacore version primarily due seeing significantly more sequences from the improved barcode capture.  Though we could downgrade to the older albacore release this would cause data loss, correct?

**Comment by jts** [comment] 2017-07-19 16:16
@cjfields did you run MinKNOW local basecalling?

**Comment by jts** [comment] 2017-07-19 18:03
@cjfields #194 is now fixed

**Comment by devindrown** [comment] 2017-07-19 19:55
I created a subset of my fast5 files and used [picopore ](https://github.com/scottgigante/picopore)to remove all previous basecalls. I then used Albacore 1.2.4 to basecall. I extracted the reads using the -b albacore option.

I continue to get the same error message.
 `error: could not parse model string:`

Attached is a fresh fast5 file.

[stuart_20170316_FNFAF16106_MN20458_sequencing_run_AntiRes_MD_20170316_55189_ch102_read610_strand.zip](https://github.com/jts/nanopolish/files/1160296/stuart_20170316_FNFAF16106_MN20458_sequencing_run_AntiRes_MD_20170316_55189_ch102_read610_strand.zip)

**Comment by jts** [comment] 2017-07-19 20:53
Thanks, that is helpful. I think I know what the problem is now and I can provide a fix later.

**Comment by devindrown** [comment] 2017-07-20 18:42
When you say use the 1D reads, would you recommend using both template and complement 1D reads? Ideally, they should align to the same place in the draft genome.

**Comment by jts** [comment] 2017-07-20 18:43
The complement data for 2D has always been quite variable in quality so unless you are limited by coverage (<50x) I would suggest just using template.

**Closed** 2017-07-28 17:31 UTC
