### ISSUE TITLE
Error 33

### ISSUE THREAD

**Issue by dmacmillan** [jts/nanopolish#115] opened 2017-02-22 16:39 UTC
nanopolish crashes:

```
registering model t.007-base
registering model t.007-ONT
Warning: 14311 variants in span, region not called [10 3922]
Warning: 289 variants in span, region not called [3873 4104]
Warning: 5860 variants in span, region not called [4055 5625]
Warning: 30089 variants in span, region not called [5606 18681]
Warning: 3682 variants in span, region not called [18644 20457]
Warning: 2372 variants in span, region not called [20420 22197]
Warning: 289 variants in span, region not called [22202 22518]
Warning: 4407 variants in span, region not called [22514 25314]
Warning: 1502 variants in span, region not called [25274 26439]
Warning: 304 variants in span, region not called [26450 26722]
Warning: 136 variants in span, region not called [26705 26918]
Warning: 6666 variants in span, region not called [26945 31392]
Warning: 377 variants in span, region not called [31478 31828]
Warning: 3681 variants in span, region not called [31917 34480]
Warning: 3696 variants in span, region not called [34455 36148]
Warning: 3707 variants in span, region not called [36150 37228]
Warning: 98 variants in span, region not called [37374 37603]
Warning: 158 variants in span, region not called [37822 38028]
Warning: 513 variants in span, region not called [38367 38644]
Warning: 1996 variants in span, region not called [38859 39877]
Warning: 7396 variants in span, region not called [39849 43887]
Warning: 427 variants in span, region not called [43895 44224]
Warning: 587 variants in span, region not called [44213 44536]
Warning: 661 variants in span, region not called [45399 45973]
Warning: 321 variants in span, region not called [45924 46195]
Warning: 5238 variants in span, region not called [46146 48081]
Warning: 346 variants in span, region not called [48038 48331]
Warning: 239 variants in span, region not called [48297 48574]
Warning: 234 variants in span, region not called [48528 48796]
Warning: 435 variants in span, region not called [48746 48999]
Warning: 537 variants in span, region not called [49379 49747]
Warning: 393 variants in span, region not called [49964 50230]
make: *** [tigs] Error 33
```

makefile command is:

```
tigs: reads.eventalign.sorted.bam.bai
        python ${NANO}/scripts/nanopolish_makerange.py draft.fa | ${BREW}/parallel --results nanopolish.results -P 8 ${NANO}/nanopolish variants --consensus polished.{1}.fa -w {1} -r reads.fa -b reads.sorted.bam -g draft.fa -e reads.eventalign.sorted.bam -t 4 --min-candidate-frequency 0.1 --models nanopolish_models.fofn
```

Don't mind the variables, they are simply paths to executables. Any idea what this error means?

**Comment by dmacmillan** [comment] 2017-02-22 17:32
Interesting, I will investigate further. The alignments were generated using the main github page. Are you referring to the reads->draft alignment or the event alignment?

**Comment by jts** [comment] 2017-02-22 17:35
read-to-draft is my first thought, since it is used to generate candidate alignments. I'd have a quick look at the alignments in IGV or some other genome browser.

**Comment by dmacmillan** [comment] 2017-02-22 19:57
This looks like a mess to me, but then again I don't have much experience with ONT. What would you make of this?
![capture](https://cloud.githubusercontent.com/assets/5533649/23229685/04feb9a2-f8f6-11e6-842f-026b2f26ba6a.JPG)

**Comment by jts** [comment] 2017-02-22 20:25
Yeah, that doesn't look right - the second read from the bottom in particular looks completely misaligned.

**Comment by dmacmillan** [comment] 2017-02-22 21:42
Seems this isn't necessarily a nanopolish issue, I am going to run some experiments and see if I encounter the same issue. Mainly I found that not all of my reads were being aligned due to extraction limiting sequences to only 2d, whereas this draft is composed of an assembly of template, complement, and 2d

**Comment by jts** [comment] 2017-02-22 21:47
Ok, let me know if I can help.

For R9.4 data I think the best setting for `nanopolish extract` is `2d-or-template` - you typically don't want all three read types as you'll double-count strands when polishing (the template and complement strands would be used twice each).

**Comment by dmacmillan** [comment] 2017-02-22 21:48
It's strange because I was able to yield a more contiguous assembly with nearly double the N50 using template, complement, and 2d as opposed to just 2d alone. Assembly was generated using Canu and re-scaffolded using LINKS

**Comment by jts** [comment] 2017-02-23 14:08
Genome assemblers typically treat reads as independent observations - using all strands from an ONT read will break this assumption and the assembler may have unexpected behaviour (like generating misassemblies). I would treat the `all` assembly with caution.

**Comment by jts** [comment] 2017-03-16 15:36
I'm closing this issue, if you still have issues with your assembly feel free to re-open.

**Closed by jts** 2017-03-16 15:36 UTC
