### ISSUE TITLE
Segmentation fault in methylation calling

### ISSUE THREAD

**Issue by tungufoss** [jts/nanopolish#580] opened 2019-04-05 16:32 UTC
I've been running **v0.11.0** in my methylation pipeline. I've run some on several hundred flowcells. I got a multi-read fast5 that results in a segmentation fault. I updated to latest release **v0.11.1** and a still get an error - and only for this particular fast5, although slightly different. Do you recognize this error?

## nanopolish version 0.11.0
```bash 
==> test/log-44567690.out <==
rm -rf /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output && mkdir /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output;\
rsync -aL batch_69.cpg.methyl/fast5/batch_2/ /tmp/tmp.kAmxQDerDB-methyl-sji44567690-input/ || false; \
        cp batch_69.cpg.methyl/batch_2.methyl.parse /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.methyl.parse;\
cp batch_69.cpg.methyl/batch_2.fa /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.fa; cp batch_69.cpg.methyl/batch_2.bam /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.bam; cp batch_69.cpg.methyl/batch_2.bam.bai /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.bam.bai;\
echo -e "TIME\tpreprocessing\t${SECONDS} s\tMove central to local" | tee batch_69.cpg.methyl/batch_2.methyl.log;
TIME	preprocessing	12 s	Move central to local
make -f /nfs/odinn/users/helgain/git/ONT_tools/damp/Makefile /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.fa.index.readdb F5DIR=/tmp/tmp.kAmxQDerDB-methyl-sji44567690-input PARSE=batch_69.cpg.methyl/batch_2.methyl.parse | tee -a batch_69.cpg.methyl/batch_2.methyl.log;\
echo -e "TIME\tmethylation\t${SECONDS} s\tindex" | tee -a batch_69.cpg.methyl/batch_2.methyl.log;
make[1]: Entering directory `/nfs/odinn/users/helgain/git/ONT_tools/test/issue135'
/nfs/prog/bioinfo/apps-x86_64/nanopolish/nanopolish-v0.11.0/nanopolish index -d /tmp/tmp.kAmxQDerDB-methyl-sji44567690-input /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.fa --verbose |& tee /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.index.log.tmp
[readdb] indexing /tmp/tmp.kAmxQDerDB-methyl-sji44567690-input
[readdb] num reads: 8000, num reads with path to fast5: 8000
mv /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.index.log.tmp /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.index.log
make[1]: Leaving directory `/nfs/odinn/users/helgain/git/ONT_tools/test/issue135'
TIME	methylation	8 s	index
/nfs/prog/bioinfo/apps-x86_64/nanopolish/nanopolish-v0.11.0/nanopolish call-methylation -t 1 --reads /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.fa --bam /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.bam --genome /nfs/odinn/data/reference/Homo_sapiens-deCODE-hg38/Sequence/WholeGenomeFasta/genome.fa --methylation cpg --verbose --progress >> /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.methyl 2>>batch_69.cpg.methyl/batch_2.methyl.log;\
echo -e "TIME\tmethylation\t${SECONDS} s\tcall" | tee -a batch_69.cpg.methyl/batch_2.methyl.log;

==> test/log-44567690.err <==
/bin/bash: line 1:  3511 Segmentation fault      (core dumped) /nfs/prog/bioinfo/apps-x86_64/nanopolish/nanopolish-v0.11.0/nanopolish call-methylation -t 1 --reads /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.fa --bam /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.bam --genome /nfs/odinn/data/reference/Homo_sapiens-deCODE-hg38/Sequence/WholeGenomeFasta/genome.fa --methylation cpg --verbose --progress >> /tmp/tmp.kAmxQDerDB-methyl-sji44567690-output/np.methyl 2>> batch_69.cpg.methyl/batch_2.methyl.log
make: *** [batch_69.cpg.methyl/batch_2.methyl] Error 139

````
## nanopolish version 0.11.1
```bash 
==> test/log-44567686.out <==
rm -rf /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output && mkdir /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output;\
rsync -aL updatednp.cpg.methyl/fast5/batch_2/ /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-input/ || false; \
        cp updatednp.cpg.methyl/batch_2.methyl.parse /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.methyl.parse;\
cp updatednp.cpg.methyl/batch_2.fa /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.fa; cp updatednp.cpg.methyl/batch_2.bam /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.bam; cp updatednp.cpg.methyl/batch_2.bam.bai /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.bam.bai;\
echo -e "TIME\tpreprocessing\t${SECONDS} s\tMove central to local" | tee updatednp.cpg.methyl/batch_2.methyl.log;
TIME	preprocessing	10 s	Move central to local
make -f /nfs/odinn/users/helgain/git/ONT_tools/damp/Makefile /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.fa.index.readdb F5DIR=/tmp/tmp.iOJBr5IDYr-methyl-sji44567686-input PARSE=updatednp.cpg.methyl/batch_2.methyl.parse | tee -a updatednp.cpg.methyl/batch_2.methyl.log;\
echo -e "TIME\tmethylation\t${SECONDS} s\tindex" | tee -a updatednp.cpg.methyl/batch_2.methyl.log;
make[1]: Entering directory `/nfs/odinn/users/helgain/git/ONT_tools/test/issue135'
/nfs/fs3/apps/users/helgain/github/nanopolish/nanopolish index -d /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-input /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.fa --verbose |& tee /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.index.log.tmp
[readdb] indexing /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-input
[readdb] num reads: 8000, num reads with path to fast5: 8000
mv /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.index.log.tmp /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.index.log
make[1]: Leaving directory `/nfs/odinn/users/helgain/git/ONT_tools/test/issue135'
TIME	methylation	8 s	index
/nfs/fs3/apps/users/helgain/github/nanopolish/nanopolish call-methylation -t 1 --reads /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.fa --bam /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.bam --genome /nfs/odinn/data/reference/Homo_sapiens-deCODE-hg38/Sequence/WholeGenomeFasta/genome.fa --methylation cpg --verbose --progress >> /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.methyl 2>>updatednp.cpg.methyl/batch_2.methyl.log;\
echo -e "TIME\tmethylation\t${SECONDS} s\tcall" | tee -a updatednp.cpg.methyl/batch_2.methyl.log;

==> test/log-44567686.err <==
/bin/bash: line 1: 31198 Killed                  /nfs/fs3/apps/users/helgain/github/nanopolish/nanopolish call-methylation -t 1 --reads /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.fa --bam /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.bam --genome /nfs/odinn/data/reference/Homo_sapiens-deCODE-hg38/Sequence/WholeGenomeFasta/genome.fa --methylation cpg --verbose --progress >> /tmp/tmp.iOJBr5IDYr-methyl-sji44567686-output/np.methyl 2>> updatednp.cpg.methyl/batch_2.methyl.log
make: *** [updatednp.cpg.methyl/batch_2.methyl] Error 137
slurmstepd: error: Detected 1 oom-kill event(s) in step 44567686.batch cgroup.
````

**Comment by jts** [comment] 2019-04-05 16:37
Hi @tungufoss,

This line:

```
slurmstepd: error: Detected 1 oom-kill event(s) in step 44567686.batch cgroup.
```
suggests that the out-of-memory killer terminated nanopolish. If you try to re-run the task with more memory does the error go away?

Jared

**Comment by tungufoss** [comment] 2019-04-05 16:44
I'll retry now with 24gb. I ran it previously with 10gb. Note that similar yet _successful_ runs only used about ~2gb. So I'd assume the `oom-kill event` was due to the job being killed.

**Comment by jts** [comment] 2019-04-05 16:47
I think the step that consumes the most memory is computing the read-to-event alignment. I've seen it use an unexpectedly high amount of memory in rare cases but haven't figured out why. If you can isolate the read that causes the problem I'd by happy to take a look at it in more detail.

**Comment by tungufoss** [comment] 2019-04-08 09:46
Increased the memory as suggested, and now the error message says it seg faults (as in prev. version):

```bash 
updatednp-44581275.err
/bin/bash: line 1:  5485 Segmentation fault      (core dumped) nanopolish call-methylation -t 1 --reads /tmp/tmp.8YZ6dwnWOf-methyl-sji44581275-output/np.fa --bam /tmp/tmp.8YZ6dwnWOf-methyl-sji44581275-output/np.bam --genome /nfs/odinn/data/reference/Homo_sapiens-deCODE-hg38/Sequence/WholeGenomeFasta/genome.fa --methylation cpg --verbose --progress >> /tmp/tmp.8YZ6dwnWOf-methyl-sji44581275-output/np.methyl 2>> updatednp.cpg.methyl/batch_2.methyl.log
make: *** [updatednp.cpg.methyl/batch_2.methyl] Error 139
```

I'll see if I can send you the file in question.

**Comment by jts** [comment] 2019-04-08 13:15
Ok thanks, the read would be very helpful.

**Comment by jts** [comment] 2019-04-26 16:30
Hi @tungufoss,

Thanks for providing the data, I was able to reproduce the problem easily. The problem was fairly simple, the read was so long that using a 4-byte integer as an index into an array wrapped around to a negative value. With the latest code the seg fault should no longer happen but methylation calling is extremely slow for the example BAM because it contains many supplemental alignments for the long, probably erroneous read.

Jared

**Comment by tungufoss** [comment] 2019-04-26 18:24
I figured something like that must be the case when I saw how ridiculously large the read was.  Everything else has run smoothly. 

I’ll update and retry.
Thanks for looking into it! :)

**Comment by jts** [comment] 2019-10-21 18:28
Hi @tungufoss, is this still an issue or can I close it?

Jared

**Comment by tungufoss** [comment] 2019-10-22 00:04
Yes, this is resolved. Feel free to close 

/Helga

**Comment by jts** [comment] 2019-10-22 14:32
Great, thanks

**Closed by jts** 2019-10-22 14:32 UTC
