### ISSUE TITLE
Less "PASS" reads in the recent nanopolish polya

### ISSUE THREAD

**Issue by ko2344** [jts/nanopolish#545] opened 2019-02-20 13:34 UTC
Hi, I am facing a problem that I cannot figure out why.
I've analyzed polyA length using nanopolish polya. It had given plenty of reads with PASS qc-tag before, however, the results of my recent trials were quite disappointing. Although the Q scores and the throughput were improved, QC of most reads shows "NOREGION", and there are much less PASS than expected. 
Previously, I got 86MB (~880K lines) of tsv file after grep PASS from 1.2M reads. ~48MB tsv from 0.75M, and ~25MB from 0.45M.
Recently, I got only 15MB tsv from 0.75M, and 7.6MB from 0.45M.
I realized that it started when the kit was switched from SQK-RNA001 to SQK-RNA002.
The other workflow of the analysis is same in all the above experiments. 
Do you have any idea why this happened and how I can solve it?
Thanks!

**Comment by jts** [comment] 2019-02-20 13:36
@paultsw can you look into this? We'll need to understand the changes between RNA001 and RNA002 kits. @ko2344 could you provide us with example reads so we can test?

**Comment by paultsw** [comment] 2019-02-20 13:42
Hi @ko2344 , I'd be happy to trace the execution of the program on some example reads if you can provide them! We trained our models on SQK-RNA001 so it may be the case that we need to re-tune them and provide an option for SQK-RNA002.

**Comment by ko2344** [comment] 2019-02-20 13:52
Hi @jts and @paultsw, Thank you for your reply. I am currently out of the office, but I will of course provide you example reads shortly!

**Comment by paultsw** [comment] 2019-02-21 14:22
Hi @ko2344 , just wanted to confirm that I've received the data you've provided. We're looking into it now.

**Comment by jts** [comment] 2019-02-21 14:23
Hi @ko2344,

What version of the basecaller, and what parameters, did you use?

**Comment by ko2344** [comment] 2019-02-21 14:45
Hi @paultsw Thank you! 

Hi @jts I used Guppy v2.3.1. Also tried v2.1.3., but there are no difference in the final nanopolish polya output.

Below the parameters I used: -f FLO-MIN106 -k SQK-RNA002 --qscore_filtering --calib_detect --min_qscore 5 --reverse-sequence on --u_substitution on --recursive --cpu_threads_per_caller 12 

Although I used the pram --min_qscore 5, >95% of the reads are Q>7.

**Comment by paultsw** [comment] 2019-02-21 20:21
@ko2344 , just wanted to give you a quick update: in your reads, we noticed a difference in the picoAmp signal trace of the reads compared with the picoAmp signal trace of the SQK-RNA-001 reads. This difference is causing an internal segmentation algorithm in the `nanopolish polya` subprogram to make errors in some cases.

We're currently inquiring to figure out the root cause of this difference in the signal traces between the two kits. In the meanwhile, we plan on creating a branch in this repository that fixes this issue; however, we don't plan on merging this new branch with the `master` branch until we find out what's causing the difference (it could be the kit, but it could also be something upstream).

We plan on releasing the branch containing the fix relatively soon. Would you be interested in running this fixed version on your reads, once we push the updates?

**Comment by ko2344** [comment] 2019-02-21 21:57
Hi @paultsw, Thank you so much for the update! FYI, SQK-RNA002 includes a new Flow Cell Priming kit, which is used instead of RRB buffer to prime flow cells. Is it possible that this kit  causes the problem? Also, in the MinKNOW setting, I specified the kit "SQK-RNA002". 
And yes, I'd like to run the fixed version of the reads. Thanks!

**Comment by paultsw** [comment] 2019-02-28 15:01
Hi @ko2344 , we've just pushed a new branch called `sqk-rna-002-modelfix` which has a slightly modifed model in the `nanopolish polya` subprogram that should resolve some of the issues you experienced.

Would you mind re-compiling nanopolish and running it with these new changes and letting us know how it performs? If possible, we'd also highly appreciate seeing the resulting TSV file from a run of `nanopolish polya`. We've backtested the new model on `SQK-RNA-001` control data and it seems to give the same results; it also now returns a `PASS` on all of the reads you've shared with us and the segmentations now look correct, but we're eager to see how it performs on a larger pool of `SQK-RNA-002` reads.

You can compile the newer version of nanopolish by cloning the repo (with the `--recursive` flag) and using the following commands:
`$ git checkout sqk-rna-002-modelfix`
`$ make`

We'll be keeping this new model in this branch for now until we can perform further validation on a bigger batch of control datasets sequenced with `SQK-RNA-002`.

**Comment by ko2344** [comment] 2019-03-05 09:57
Hi @paultsw, I have just finished processing a set of data using sqk-rna-002-modelfix, and I would like to share the results. 

In 3 different SQK-RNA002 data with ~1.4M reads, sqk-rna-002-modelfix gave ~4 times more PASS reads (79~82% of the total reads) than the normal version (21~23% of the total reads). Also, I noticed that all of the RCS reads in 3 samples are tagged PASS.

I will share the results once I finish comparing the results from SQK-RNA001.

I'm wondering what could be the reason of the difference in the picoAmp and why RCS reads were not affected at all. All the procedure and the materials for polyA RNA isolation were the same, and the only difference is the kit for library prep.

**Comment by paultsw** [comment] 2019-03-13 15:18
Hi @ko2344 , just to clarify: did you observe the PASS rates increasing from 21-23% to 79-82% on your datasets?

By RCS reads, are you referring to reads from a control transcript (e.g. yeast enolase)?

In our communications with ONT, we have learned that there were indeed some minor physical changes to the adaptor when going from SQK-RNA-001 to SQK-RNA-002, which we had to account for in our computational models --- hence the new branch.

Thanks for sharing!

**Comment by ko2344** [comment] 2019-03-14 02:33
Hi @paultsw, I didn't realize that something went wrong in the last comment. Sorry about that! Yes, PASS rates increased significantly from 21-23% to 79-82%. I used them for the downstream analysis, and it seems that pA length in those PASS reads are plausible. RCS is a control transcripts. 

I compared the previous and sqk-rna002 model for the data obtained using the sqk-rna001 kit, but there are no difference in the number of PASS reads between them. 

Thank you!

**Comment by paultsw** [comment] 2019-03-14 12:27
Sounds great, @ko2344 ! Do you have any other related issues you'd like to mention regarding the `polya` subprogram? (If not, do you mind if I close this issue?)

@jts , my opinion is that we should close and make a temporary note somewhere in the documentation that SQK-RNA-002 kits have a tentative (but unvalidated) fix in this `sqk-rna-002-modelfix` branch; we should merge the branch into `master` once we can further validate that this new approach works more broadly on a larger class of well-characterized samples. What do you think?

**Comment by jts** [comment] 2019-03-14 13:20
Since we've seen that SQK-RNA001 results are unaffected, I think it is better to merge this change into master rather than making a note in the documentation which some users may not see.

**Comment by ko2344** [comment] 2019-03-14 13:33
@paultsw , I don't have any more issues. Thank you again for your help!

**Closed** 2019-03-14 19:31 UTC
