### ISSUE TITLE
First round of nanopolish couldn't identify errors in thousands of error-containing assembly. 

### ISSUE THREAD

**Issue by NewBioInfo** [jts/nanopolish#557] opened 2019-03-10 03:32 UTC
This is my first time writing in github so please forgive me if my question is not well formated.
I got fastq files from 1D2-flowcell using Albacore (v2.0.1) and trimmed it before performing assembly with Canu. For correcting error in assembly, first indexed the fastq files, aligned using BWA-mem, and then used nanopolish. Nanopolish resulted in .vcf file with no  nucleotide changes and the error file had following message.

[post-run summary] total reads: 29329, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 29406

First I thought that I have error-free genome and then I aligned it against its parental genome (published) and found that there were thousands of InDels. It doesn't make sense as they are isolgenic strains. I really need to assemble and publish three bacterial genomes in next 2 months. Please help me correcting thousands of InDels.
Thank you.

**Comment by jts** [comment] 2019-03-10 03:35
Hi,

That message indicates nanopolish was unable to use the fast5 files for
your run. What messages did the 'nanopolish index' step print? Can you
provide the complete list of commands that you ran?

You might also try the medaka polisher, which works well.

Jared

**Comment by NewBioInfo** [comment] 2019-03-10 04:29
Thank you very much for quick reply. The commands are as follows...
$ Indexed using BWA
$ bwa mem -t 22 -x ont2d Canu_pair/assembly/contigs.fasta Pair_pass_trim_Nanofilt.fastq | samtools sort -o Nanopolish/Canu_Nanoploish_sorted.bam -m 6G -T temp.tmp
$ Indexed using Samtools
$ ~/nanopolish/nanopolish index -d fast5/ Pair_pass_trim_Nanofilt.fastq

[readdb] indexing fast5/
[readdb] indexing fast5//101
[readdb] indexing fast5//0
[readdb] indexing fast5//1
[readdb] indexing fast5//100
[readdb] indexing fast5//102
[readdb] indexing fast5//105
[readdb] indexing fast5//10
[readdb] indexing fast5//103
[readdb] indexing fast5//104
[readdb] num reads: 61762, num reads with path to fast5: 31957


$ ~/nanopolish/nanopolish variants --consensus -t 22 -p 1 -o Nanopolish/Try09-03-2019/polished1.vcf -b Nanopolish/Canu_Nanoploish_sorted.bam -r Pair_pass_trim_Nanofilt.fastq -g Canu_pair/assembly/contigs.fasta > Nanopolish/Try09-03-2019/nanopolish.log 2> Nanopolish/Try09-03-2019/nanopolish.err


Please let me know if any other information required.

**Comment by jts** [comment] 2019-03-11 20:21
can you show me the results of the command `head -40 Pair_pass_trim_Nanofilt.fastq`. I suspect the problem is due to 1D^2 reads, which nanopolish doesn't currently support.

**Comment by NewBioInfo** [comment] 2019-03-12 01:11
The output was very long. I have removed some nucleotides and represented them as "...................." in between nucleotide sequences but quality scores are kept as they are.

$ head -40 Pair_pass_trim_Nanofilt.fastq
@a70bd46f-c322-44c5-b7c0-b35dfae38bfdbdf6e3d2-79e7-4b68-9536-8586eaf37fe4 runid=fd2ffc3e1efbc756ab226b3a522a9465831a33cf read=965 ch=1 start_time=2018-10-03T22:12:06Z
CGGCAGGCCGTACTTGTTGGCGAACTCGAAGTCGCGCTCGTCATGGCCGGGCACCGCCATCACCGCGCCTT..............................CATCCTCGG
+
76=:-,5950.42/3:0753.,27:8;4355=8/,(&),/6-*+:=2.=(333;/@<2:?455C4@;B<4994763+03C4560-+18<;?=;D95864+*'&&)/7,*230.+&#.9>?E6;53%(,93'+*;44@>EBE9=+1@13>3*/71,47?BFCGEB>B>26,-2)/0,+%'*'*.200**+1,:=CE>B5B:<<=0<1118>;5)65.6'@B?B96.&(+,11-0+-5(/-/0119<AB/0),'4-<6,(392778,593:31.050,05-/8A7<7,-5::29636=75252<?-++*+(.-7;<?9:@A>@66602<>g)*,2+1-8*2-:,0?B=0=?=3=<?<97930E?C<.3,-011.2)*(*''8339.)/).)*'&)'..16577:9J<J>D::C@B>B;;)(+***664301:?+8>A7FB;??6606<3:889.*'*3'0+--(.46<1.>4B>60).6(0=-/A=:==;;>=4(./0:5.@)2:D/**+>;,,7+.-6---/-268708*--.768'1,&$**)+.,+'9'82++,*-2*C@=@76644/,*+0491.-&+(+*&0-0-/601CA;,.*&89>7D.(//07DC8==;:31,,*60DE48A@25==@@@:ED<27.7:6B8-L,1550;770AD8@972<<>6?9-;836-,*.)*;>333661(%-%(,2-13:677-/-,*2.-)8.B44215:6>;32426@?B@G=83')2.A1(/,3B:;:91,.?:B2-).$:<<6@?A,@@:4D[hI:??<?CBBAEA87D8<424;80D67:7=DBA<3<:76:0>2@@5**(05;/9:=<36/+&**(2457@7:/@6/(5>A=?>?10/.3:51X6<8<<@B09ACA2:3565=:641/5.?.657./&5,258524.400,22:20<89736)4.@7>;@24<09=@@AA&.29.?1=>C@=94675;-,-5-2BC;:F:8534+*/143152./(;8<=DEGCA@8AA4-8/1-(-..AAC?<<5165:-8-0>;684617870/=AH=85;)0680-1E=G;98<<=4-,7-,&)6)..:4A;5?,-5;*>:17-4,*-++1>/5826>0,,1+543/<=>;=0;99613A@AM;HH>346CCA<5;?43,:?<=&*114854/B@DB>:.1)(&%%-#,*)13782=0--18234(-.)9669>20329636?<@7,8297?3<2<767<8B334461758:8202200++)*0.704<=<?/6.)0%%&(*4:87'0)*0)1++2BBC<+-+0-68:16=5;5235&-/-.6-+.7.+7102)7%%+-,0949:=/04544+24@><@?C..(1;EA6-/4)1-')4,5593;46:<:87<---/2'(5+48?>;B3/<+&*(+41-2426:433;2+2?=>:10/.4,/1043188241018;86,6.&,%.&(-B?77451?2..'*+)-5;@A<=.543:8046&(*/(%$)71+02(0/+/'%'())*432-21('1<104,-1<<I<=9D:3.2012(-;.A5<=A@?B?C@43//.1-<>=@4C:B4<5;FcI8D.;8HG1*,-43(.B1,.'3:1,)-+.)'+1<552241(&@@/03*'65).&&)+2>G?7D3>/=0-@;=4<0,;-0=401)+29/1.04>669<C2A++&1++*,6:AEB?CA>A1</1//,+1)(5)0*+.5072344-+,17G4),11),)+&+)(4+(40<=A=8DB99687?&4&++141;;2BGDHB:?@=)5<K4D0?>@/8@<):.877=00280>AA598<*<@?@?E/?/8<+0:81,**-+)57<.9725179+996731977=><44<1167/60?9**+/-..,+=;7806-:IIQ3AAA.-3)*+?CGF-760/.-)293**++.76AEBA==?+/085@20,1,.*.B<<:8(6BA>/.7,+1.+.013654KF.3444BCAE87277?
@57d67d6d-4644-4071-8f23-289cd5758dfbb9332f37-7195-4e69-9f25-c2691112785f runid=fd2ffc3e1efbc756ab226b3a522a9465831a33cf read=1219 ch=1 start_time=2018-10-03T22:33:01Z
CATCGCTCGCCCTTGCCTTCTGCGCCCGGTCCAGCCGGCAGCAAGCCGATGCGCCTGCCACTGGCGCAGTTCCGGGTCCAGGCAACAACTCAGGCCTTGCGCGACCAGGCCGGCAGCGCCTGGCTGCGCGCCGCTTCGTCGAGGCCGCAGCGCCTCGCTGGACAGCACCAGTTCGCCGACCCGGCGCT.......................GGAACGCTTCGAACATTTCAGGAAGTCATCGGCAAATGCCCGGAAGTGCTGGAGTACATACGGTCACCGGGATGGACGCGGACTACCAGTTGAAGGTCGTGGTGCCGGACATGGACCATTACCAGAAACTCCTGCTGGTACCCTGACGCATCGAGGGGGTCTCCAGCGTGCGCTCCAGCTTCGTCCTCAACCAGGTGCTGGCGAGTAC
+
,$(1.323.@7)()/,-'(+-.'/,41('0)21,1/---)&((+',-95(++....12*07%457:<8@.&,),(;04-'.22;*797)%)%&*6-%*,+'&%*2,*-43.*%$,&..21%&,1,,4//*/.050)/,4-*)$77-.('.22:14=;8387-/,7<9Fg28.32>;>0324*/1&'(*)**)44-/2/,+.()(***()'(&0-4,85$&'*4+.+(+'))(&&&&%**2-<@?6..00111&&))'((&,()*/,0,1..+11(-+20('''&*1502-,'%')'+',((+*+*-+''./1*0*)(/*+./,111+.((&%$$%%%+.(/)+3-''%%&(*/0..,,+,)10'(1(*.3/4-,--1-55240333273=8>@6-*'%%$%*+-..*.-)'(%'''#$&&1)&142*,)%*))2210.)+)*+&$%$%$%1/''&&#&%(3/*,*(+/1()(**:&89*()('&%+/5-0/)*3/++)'(0*)*()&(5*)3&)(+,+*)*)/,,,30*'&%*)*+(.;-1;.3/61,-+'&'&$&'$$&()(-0-++*+250/&,-,)/(45'-(),*5544/,.31,6)2149558B13,-0()'+(.5/0-+2<3;:97'/)'*/&$-(,&5*./66--&***&*$)+-..<@CE>75:%*1,.')'(()),000-/.03/2**)*,015>2)-*-/2@289:65799B0-3,-(0-*%-,,/65,/.+79.6.1.+.0+,%,*)/)957F;B54**()A2,C>30.*-(/(.)06*2*-,03450'413-)'//+,1(+<>;:<:@HEO)D=;=00:.&-4GJB+-,5'D9+***-/;>000..$)'10-*$.1-468;.+)'&-+.2=?A4=16CB.3-336882+-./426;:5/++/.-1/(*5263>@/5BC0290787?@=G/,+(-5=.-,68:?.A=?@445546;E=<E1..?9;D:>C617855;1/+&/08-4/;3/603:1&%%/001H,0357552;5105<5=A:-26;?ACC>@9(CD)-1.'((*?@F?0?<701*'41.(%(',1,2-$/4>/=*)2/4347.6.1,577:4-/4568-+57/,63687?@@A<63.11=050-(,01A@FE;27,2AGCC?C=6?E>B.3165C@;@B;@G2))(3;?51211CBE@75*)8-97?C@<13.-011-44*+347;60(&,*-,*(%,*+()'*.14.(0&,1<.-+,2.*&,/,/,///+13-6IAA>8<<@:<A;8+-130.+7)')&,.265/287)('&''+-,+113/5'('%&'&'&)*&%%&--*7.)4.0635)4*(+(+.*-.,/0+6<879(9,&./*&%+62624/,--/++4,&$(*7:4<@@A0,4;<>002/*+*&,2-+(''+)-2+.,,)0,2@0-,('()**/340643221.4)(*,-355/**,-**%%%(+%)'$+)%+(,')128<7<;+*(()35899955.0,/0,450..*(*+%$*)/*)&++-,*.'..7;/5($&%#%*'2/,(%))(&.3.+)+/25&(%%'')(('+.-34131?;(:()'%)'10/::0/1100,-8<62,+)-,--)0-),+*,,.+/748,,-)(&0A+&)%'/2/(+/)0((+++2-*(.*,)(),+*&,840--.+14140)'(*.*,*()*-'0))&1*&0-;98<.<2<393DE=4-)'(%&-426,/0358;<64;:84*,*8EFC/137)-312=28?60=.9*@?D?C790.5-216;714-190),,*/-1=:=3497388-5100CDA=4D(334)-*('+%$#$&+1546BDA2.,./(+;,/</-4:.AAB73.)%$)0))94/-5741156668..=A@/-..',22/.-138;>1*+5/450201')409<9;>@<<D61+===:EG><BH33729F7?9381%@.0=E>1,=2::)B2E=>11-/B46+B200124.,2>=>.1;997643,*)'*353,.(',(--/(3.@4627:8/3??+,&*))(CLCD<<;<4630&40,707??68-66=&()*1:041D-D=ACD5@-3/01:7//-.46EE3=,++++D?<1.6.3--,?A7>8B?DBBC/?CCBD?B5GC<:BA::@:73:85B965BC7/.,*-9/3'8CQUj,311))1/33+2,791)-8.2059<B::9=;J?@@;@;D9A<93;::0:7=C?>93560.,:/-822%/)83GKALG*4:A?:>I@CBA?<+*)D@44?3BB@8=:;82-0052<;/-2));=@23+376956881-.-3:D=;B@?@88.7715B;CH9,875110.-.2**666647>643/1:8769@>@FB?.-2,3:?B2/:1'+970502;><F>:3,%+-/4@?<EC>82,,),.2-%34478C;;33313/),1/0370<A?@;BAD90?91411?61?*(,1,5//-,@B;@@A41;:39A4'(423)1*C7_N:--'+.+.,?253*-,14-63BCABAD@::007;8/;5?BCB<3438:9.-),((*35@?7D54>4>9A@=/-577;2;;3;:72;?0/.433=@>>A4?34?@B>G@9C1:-.?+(.68;CD6<@600$&&-.((70>1.,///).9.0-/0>8885359-;@@A1BC>0>0*08--73CC<97:7BGF-0-0.C6/4.)4(-//01-/198809=><DIEC1H@D3?3;;5-0121;;847-=>>9>BBAAAFA@96A:AFIL3./9546<9.1213<6>54.456/><00/==&&*')29762:,2+&'-3>522536187AEE=EB=78:97ED=C)/2(-@1,<9:*55307F53rf035//),),,:36-&),07<>3<A4B=-<=7>CAA:6>;7/9C?4:2348>9=>/BHGZ?B@A>A433,(--*-+&2+35310././(+,*-(%0'1++8727599?>>;=45;427@=EEG7GEBB@=2?,0414485178%+-;AGED:8-898?7@56JB3KD3-')1(2**,//+,-+127./44++)0/1+2,+6);<10>.:9834489-/A+03465=2;1;7??6*())&((%/.2,-399565--/96614*(;?79>=DA:>6A8610*/62BB8/4*050;?@A)<3?<8.;:;555,202-04=B4<<11.ACEB212/0323B4@4>447A>?2++()')&'%&&%)),-*-32505;'%)))-,6.5.4:?3./8/.),1/4),0-,589;(((835=5;@9BFAB3470><.)2+.32/H89=3-<)23,.3.,AA;BF=:10/1//)'0/,;845+330.;89?47=A91/*790977757)9@8BAB,8C-0-8-0)((42-5231670/2=:</B<8=;92=<8.</*.-=03/A2/,,+*.5-,1900'//+22;-7'4+04;:7??CG?,5)/8:)+<=;5(.23,0.3,)(3D88324**8.=-/?+*/%,1BDNBA21/-)22D59500++-*6492@9<==?8=9/3?@555)<<>;(936=40JI988;40+/)/0=;0A?8:(49=?CCE4517/D1B240,(),(+2C@@@CGF3/('$$**-6+400,.*4'33++')*535::E@4347649:<:A10*.,/BB3:2-8<./-,0)2655:BB/<.*(++02/+/@<9;6237;;?:=:=;1B0/42/3D-9;B3289=43.11-**,/.3=82>3;<><@A::<,+37?831+-+&2,+0++++*.3-+02?4872)+14+4*,40.3:@551,1D5,-,->)&-.,--1))&')/<?<4D+9.1*:.74,0659-81/26)1+C5'*,+)71>511551.3/(+3/1/20--)*$&%&,)*97.6+5*0129973,/07.+>>661-4.0-76;<@DCFI//01,0;<A=<-<-232,0*<.C+;81432)''%&,*22/,8>(50++,//59;6./.=B48',,-/4?420.2,30//=?>?6@=A>7*////.*/,,,8A,-+++4.+38'.(2/2)*,)*)54.+*/*).118713;,86D<<827;<AD85548D2.645:0:=/(87><.)/3.02..6+++(,0&/-541097+87@50:*:('))0,+./+)&,3+)*+5@??;4%11.-4/.-**7'/'2*0**DA9H/<2>7@=F?B98<.9S6L954FHXYM=B=GHE?7455?1///81@99579>;77B02>B31EA=CA61.322A>6;8=@=ED>8=@=3220/7;)50*'(8331389;<4+0/2-11@3M1-+-.65;:>5?0/,@A=72,-1;:0@>?B0--695)-=22701<CD.1.//7<-.9;=9724111228,$-'')*))&/0,/0>*3178>?G<28454+1.,;62?5)4*13?9B?9',,,-:A4*)//&-2)5?B?5../2/65.@9>7>:==81-*/4.(,-*6<=-24+1/>D1BB<5).&',.+'&,((.)-2/203/1/+'),6+9/(,457=0B36999>>B=1121422.0(857><D:5369//,+,-*-,,'>@3<<>=;5;/==<=L3-5*0A)+8E>E><<;88,&*020)/).4K013<459<@943108*7645=><73<C8A23+-32<::70953+,2708D>,04,,:1384::97=661>A31>2-FC9101)=BAAFA@E@<,,**34-301.AE3-./++-.+/41/*)'&,))38;<95:12>67764=6321464BB;;>?<.;B8.0@AY:<7@?HHDDGF4@;2.*),80=>/3<;>=0>8>@D5A5*('.0(534/3,-1+64@HKD?+4)0,;<6D,?45869:**/(-.86;967@?19850C+(*,&&')450->9.2>84''87<,=5<<5457+0/-01./5/0/)-)..%-/4><;:+)82(,01</02,7;7=/62%+&'(+-43;>69175%$9843-1295933:860240+..,+**0(*+,-//1/$&%&$(79668<89/,1.,1*&/42/+*(-/6/-,42,48/+4;C5?9E2=9,4*-*6*01./-&,(%$%)8.62<3-4:6?A4=<56-==@>2AF001=17/&-(&,,2060205A@?59-)46)>G744,-1+1+-/0/,.0,6;.))<)*/*/,(.--1+.0,/,+),965>=,/.*,20:/C,../,/548)20@:?330024173-&'0067
@d17ad835-45fd-4e77-8efc-2f25ca2a207386ed76ae-cdd1-48ce-8be3-93b0688fb606 runid=fd2ffc3e1efbc756ab226b3a522a9465831a33cf read=1058 ch=1 start_time=2018-10-03T22:19:38Z
CATACCGGCCACCGATTGGCATGCCGCGGTCGGGATAGTGCGCGTCCAGCTCGGCGCGGATGCGCTTGAGCACCTGGTGGGTCTCCGGCAGGTTCTCGCTGCTGGTGCCGTCGCGTTCGATCAGGTAGAAGTCGCGTCCAGGCGCAGGCCGTCGACGCCCATGTCCAGCCAGTAGCGCATCACCCGGCACCTCGCGCAGGA........................TCGGCACGCTTGCACCGGCTTTTACTTTGCCGCTGACCGGCTCGTGGTAGGTGGAGAAGCCGCCGTTGCCGCCGGCAGGTTTCGGCCAGCCGCCGTCGATCGAGTTCGGTTCATAGGAAGCCCGGCCGCGGTTGATGGTCTGCCGGTGCGGCGCGTCGCTGG
+
(#%%)+).+&,''3152-3<(,*)$).)2247696?59<::<41/3+-,5778=.))&/2A=73(.'(+A-+,0(',7+3/-;:754,,(*09<41:;?>A@9'8<<531140><:?8/-3A(50,0('&'&-7?@53-**--/D0685J.0<;'7&()(D=?B@9<8@@,7<//0-02351922--46BC04699:,9-:8)',8)/1+;*-,'),//+,34;M291.310.'$'*/6;5.1.,+)6;*;;././-2:..*+-'70081*),40==2/'/***C56-?+22;A?DE83A14:;90/,/(,('';4B6.,.49.-0<6.40..-/<36=?ADBC?B>>6<37=003641/283.6610.7B?>>67657)2/,(4/7356;8>32012;?79;@;@;-)7954:.1'&&-),++)3-'*.+.5:0110,.-+,,/=A:94E46.65073'+0032/3>>FE?=>6@417+27D@A=<:73>/@<A(;>==32*1+%*-'+/1.)-%&)1273/*)-042@>7>9<=3A3B@75;/.0/0/((*/*2@B0041*:;.)(*,-0;:*9/'++,;+,1/++;2B89+3'/(,-=D6?=A@5)969;%0::/34900/**.)//1523/040-*8,.3;52+--147D==686;8:9J8:7,,)-*(/?@>78;9=*3'0=32/.2<026=</)&&$-/234)**'**+(1%*.1,611D9ECDECBBB-.9:2,J=?@<=<11/351-,+((43)(-/01=B1.:A:-<78457543354A@0-&&))'5,)132*::@DHB9622,16+***,14+1-,-/FB>>85?B@EFB;@=>222/..-+*=21..02AAF65344::;F@1>9:6)'/):?;=;8:7?B66:4/39;4A@B=?A?@>)>?@,0/%'00)-(/4..,,./-9;6B;H?-.3,268@83:')1:;/-0,)*A6371+.7/;83627A3>@3;227?>?.&),*.634B;+),)1.24.7:3.'/-//&++(*&%&.(9A.2'>4/*,//C>3AF5<3,*0154@;:2+.:>-+*((0)/289/*..;,2<F+:39DA25&413CCCBB&/88>-=::6110/25673;:10;+2:4=4(37.&*2+4:,$()$%(-0%%$'$)*5',0('(,'1/480.00(,'1010&-.+%8;B6<?01./0,;;?1//4,2579=<<:-/(&'(%*?I15;741/*,0*0/)(*(3+44-/.*&'(*,**-,*,0,+,$$#0>@=.1)2/@CG03/)*(.(18'A:96)0)/++%)3/+=002)0+0?.>'+1+5-4CBBCA.(.112,:8:94%%'$%'(,+'--4.;A>3=-*53-..115+;23-9.(,A8=3/)5525;;6+1--///331751-24040)**1534A?9=;<?;71200-.4+1>9@;<DB>=>A<9/(&%-4,8+'$01(2799,.+5*-,(&*,--DE@BGG3;:@67264=CBAAA5;8/<2+0:A0/65556189:*3)-243/.?A78894=;44;2<;1.,'*,.(,.1)-1**,?;>1>>1=>8>5254448<A>)8;:C>?@?B9+.,,01=9<==47:>>CG;-5//0531:5)''8557D@A@<=9><1136?:7A<2=4($%(+.B0719,/5894347@>=@=32-*'6*(-258B>CA0-,&%&$$2,+-)-(/4453+,'&(.2*),(*.)(+++..+%$&(005208'&.24(49695>5/(89:36>?,;;1914=&>2:)-)0//-,-,+.))4011,*8,-,,*0*%*8.+-**63526'-7=>>B24:6>;7C@EFDA?=<44555791*/..305H;<9C6:;:1*+)&5.6=>,@FCF5D<7:A;?+?4A?62;<ACC=)*,,:=,@1;2-,*0-23?:B;87/7448+*'((0)),479A?8-.')*(-3=>7=/:/)*+)%.&%7>+-1.1720902;0//9-...54<32,.,)'')*7/0(?>=267''+'&'%+)9.0/=<.-1+7@++?>3:(>FW.6@-@ECA;.);=9:0<-=81-0-1<:?/+0,//2833,9/11-9658AA6DGLA>?A:79:86976/0-*2*0-0267<(=.5=4+/))-.',0./5;9BE*2+3,55.2411,+/11--(>5337.56.&.//5:&0(02-44549-+..,3),,*%)+2//2*10)+)%&$,3:67;;7?=50<6D>:>>C6'&'-67+/011-/5*4,-/).1-+1-&))'912506;>4<=*9BDADDD0@D60//%/1,.%+%,(7AA/?.*3*6878630,5('(9:150,*..766-0-/2535686%</*1<.0525011<1'2%&()(+*,-(&-,/,-/(:4<<0?9:<<5555>C<23+.)/1*;0<7=04,>(7..1-.8(.2)&,1A?2%),=>;<?:0/4/@))(B-<@2361..+-*01052.49113-31444778:10'&')*.*8/B(*:A666..79:@+++.114432?&F4<75(*55207<6A/'.0)91>/6=819530ADD.8>9+*3<3,.=.123+*...+&+161/,00,72,0<<@655**/6;>+/54/4:18>21-8,5A=;*,?DCBA867656:&*./4/64B*==:4+12.+(,&(.:0;946,*%+;,?8?7;331114+))0*,.,+,-;2487;<;CBE667323:<?;@30*-22<799;:9>=?/.*+.10775D6:=;55567:;/0/=7664*,+,00:@C80>63668.&%+((&-+))0<99/,543&)-,+)**(+&+4=/($)($%+9:3;)*/1+*(,13+01+'?'&-(&,))-11./18*5;,-=19>3:>;*H?D654A88(4<4<B9=;3*)&*,//0&2189=5;)0-00')&--*)-+;B98368;BB7',022.86;4414?25>;9:9-7029+0,,,+27@=?5>D76=712A;';886,4:>/6+-*,0;5?<=-60,*''0+'/80)-/48;+,474311,/00.-09B>=;*1;36200?;;949FB@=A:0,6/=.+*A90C.-//+8CBI<<C86C.3,+(/+15-)0-+8/2/2/63/>0/-/+-*-1<8(8,/3:467=EK<3@001()$+*,&(-19@-5/'.).,2.>?25:JC:<=&42:+)3..>3342-/*01=/1/3@<=C19-804:0322A-95<:<EEF6B8:.41//=DC3-586@<CDCC$&,-.:=:<<A=783;3-:-/35?B42*&81/*-.6@790+)1-+--&4-=/,5.40)%&05/75H2F&;=ABHHF?<<>/3/&)82190;-)/1+6/*./025+:3,%***+),27=@@773226?837F555=523/.68.1+--1223.+5B4*(+/*+//4222208-',659087@B12/+,-.)==9;&.,+1>71243+)3)2/62&812&(*(+)/225/'0302598;.38-/>010:5:191056+--/1*.681-0/-;>D@:9<504781-4+8,-9;::6;)*,*+,48*)/&&.*+,/.00+;08-2*800974344994683,.*,8265>=76<EHHE8;875433/;-/1=7<=,+:1271J@8<>20P.;,*=/*12=4.1+(+0.+*'')1/54506/.1B:9603?22665B>C+.5=:=?@96:=2=10-0.?A:2=@953//</21>2.5/,*.*&(%/,('0'/(+B<A;<1E<@C=4@6558:;><2A@B>@<:?>?977:54,/*-&8-3777-:;>:1B3/247''+/>0'-$'&($%+*253?B31,'&++7(.$.09/(-)/.-('044-3*66CC@;10+372;+/27/5,,+.+($(**-4.3-,.584+123:7//2456<B?:;97/-)).))*$*-)*)%*7204=89<>;A1/2(@DED;FA@/EF/0D@@?A@9:5:7.*+(*<2768990--0-.,(@6129*2,)/..925C_Z<*+;.)+145C@??8F4AA=,.0)+'%&&(*:6>C@+42-44''-.797=?;@>697;26:2123.65550443.25/29>C1@2-;==>;>1@BBD0+/4+411.);>43.368.6;@7F870;2<392(135)/?9D2/38972A;480:C;;=629A1103/**1=<09AE==;<2D=;C_,-*.1687=:6180,)-,.A=/01/D;,:5994@701.8:/)A>CI>57)'+109*B1BA>;.&()*-(4-0=:57;B.=/./))'((,),5><<=-*<A8<DCC:3,(+..03=.,,(-422953563=61474989-,(-6:833266?A849/213ABDDA@EBBAA>:;2;::477BB/.(02***,0*-')(&'0)(+'*<(,,*+)5;64C677/7/,,31$,.879567.28G--+'(,$)+)*)-103,+&**+/*217?B6:<:&=,;??>A@>>=3-20/:=A479;/.//1.,0./-3-.7,++.00B/.11.28423+)),,=7=@838,./-97=?2205CA,;28/133-1:5;=7@8+9=>3+4C576-'.//.*853>?BA&'''-(+)8C<.6445B<-A798@2,,+0.C:4<)5-0:2..--)-*0/.016??;=A8D=8?D@5006,3/67@7=''')*7>%*'.:<4<><3/0./010204=28,+167-,5<?C<9-412662NKK=C=@,++;.0346/.*.3HA@74,--02(')(()2/+1;%'&@<;DC>.-+')(+2162.732+51>9445.--50.(+)1,4)*/61/,)'***4),*$,13*'+,+8<3@332<1;.+22/AA97:04.64+'4<=3=2A2632..>89;:/.,,,2=5:8FO866765*4+*8>=5/1%%%&&&('')*6587:7450.014*)9,)*-(&&%*()15*.().-./5+9+*-2&()&$.1665:5609+90,%,+3626Q524CCC9D7/-0)+.26/98.=;3:60..)-')&,,+')/*+&*,,24,,-)+1(15/-<=6=0,+0)-(*-:C2</@3,.+*89:,.+)0+50,/&)./89646858<::*8>=5>16:837.353*+)2A3250*2/+25352=>;?<:84.,&("$)),.004-1)-4:67.(+*'%/3.9;95=8,-*(,-,+&./4441157;?=;>.//)0=??,+89:=A?>4:=<>:843/5/.(-30209766=<<:AB2?<=,:=DBA-9-.7@A068A5:A@<19>A5B646%;B[<=@>=92294:7772/A1:2B3,(35,50275>D820320?*310(0.26294=?@?CA=CECGF:H?5.CEDA?390/-346*.99<=;?>AE<,.10/+>ACAD192217A<8>?:=??9?>7@AB952242ACD7<>42&*((&()&-4;=*./01-@<:82?8B23122@I>?@41>2.5@BD@E3>32EHOOFC730026:;8=D<BACACEAKsl_)'')*++-3./.858=8.-&%.+')+-.4:>;9040.+(+((+$%)+*%)+/-1<8.,(*035+82.2)&(,(+*,*9.-'+,,0)()**&+.23.=89=5%*133--'+,?3.=:9=-/=+++*)',/5.0*--5/(&)228?4/A34=>:0537983144-.-61?6289121/,/.,*(+,*-,
@427f2cb9-5cd5-4b4c-a5b1-59e496178bd5f71f32b9-00ef-468f-a095-e63250671218 runid=fd2ffc3e1efbc756ab226b3a522a9465831a33cf read=1575 ch=1 start_time=2018-10-03T22:55:24Z
ACGCCCTCGGCGCGACGATCTTCAGGTTCAGCGTGCGGCCGAGGGCGACGACGTCGCCGAGACGATCGCGGCGTCGTCGCTGTCGTGGCCAGCTCGTTGATGAAGCCACGGTCGATCTTCAGTTCGCTCGCCGGCAGGCGTTTGAGATACAGCAGGCTGGAGTAGCGGTGCCGAAGTCGTCGTGGAGATGCCGACGCCCATCGCGACAACTGCTCGAGGATCACCAGGCTGGCATCGGCATCGCGCATGGCGGTCGATTCGGTCACCTCGAGATCAGGTGGCTGGGCTCCCAGGCTGTAGCGCAGGAGTGCGTTGCGTACCGAGTCGGCAGGCGGCATGGGCGAACTGCACAGGGCGAAAGGTTCACCGCGATGTTCCAGTCCGCATGTCCGCCGTCCAGCCAGGCGCATCTGCCGACAGGCTTCGTCGAGCACCCACTCGCCGATCTGCACGATCAGGCCGGTCTTTTCCGCCAGCGGCAGGAACTGGCCGGGGGTGATCAGCCCGTGTTGGTGGATGCTCCCAGCGCAGCAGCGCTTCCACGCCGATCATCGGTCCGTTCGGCGCCAGTACCTTGGGCTGGTAGTGCAAGACCAGTTGCCGGCGCTCCAGGGCCTGGCGCAGGTCATGCAGTAGTTGCAACTGTTCCTGGGCGTTGGCGTTCCATCGAACTCTCGAAGAAGCAGTAGCCGTTCCGTCCCTGGTCCTTGGCGTGATACATCGCCGCGTCGGCATTGATAAATTCACCATCAGTCGTGGCGGTCTTTGTCGCCGGGTGCAGAGCGCGATGCCGATGCTCGCCGAGATCCACCCGTGGCGGATATCTGTACGGTTGGCGGCTTGATCCGCTTCACCAGCTTCTCGGCCAGGGTCGCGGCGTCGTAATCGGCGGGCTCTCGGGCCTCGATCA.............

**Comment by jts** [comment] 2019-03-12 02:08
Thanks. It looks like for 1D^2 the read ids are merged together. Nanopolish won't be able to handle the reads in this format. You'll have to basecall the reads using the normal basecaller (1D), then use the 1D-basecalled sequences with nanopolish. You can use your existing assembly with the 1D reads, you don't have to re-run canu.

Jared

**Comment by NewBioInfo** [comment] 2019-03-12 13:10
Thank you very much. Really appreciate for your time. I will try with 1D reads.

**Closed** 2019-04-03 14:41 UTC
