### ISSUE TITLE
Nanopolish variants fails to write to vcf

### ISSUE THREAD

**Issue by mh124** [jts/nanopolish#295] opened 2017-12-13 10:44 UTC
I am failing to get the vcf output file..  When I run the command with only nanopolish variant -r, -b, -g and --ploidy 2 it seems to be running fine, no errors come up. However, no vcf output file is generated. 
When I add the command -o variants.vcf to it, it gives the error 'Segmentation fault (core dumped)'

The exact code I ran was: 
nanopolish/nanopolish variants -r fastq_runid_23aec70ebd0c24f4b56adcc05524efe4cc5d77d5_0.fastq -b reads.sorted.bam -g canu_BC12.contigs.fasta --ploidy 2

Anyone any idea what I'm doing wrong?? (I'm pretty new to all this..)

**Comment by jts** [comment] 2017-12-13 13:37
Hi,

You're probably trying to call variants over too large of a reference region. I suggest adding the argument `-w contig_name:start-end` (replacing `contig_name`, `start`, `end` with the coordinates you want) to narrow the region. The seg fault is probably because you ran out of memory.

Jared

**Comment by mh124** [comment] 2017-12-14 10:00
Hi Jared, 

The sequence data is a ~1200 bp amplicon. (and about 2000 reads, so not a huge dataset at all). When I run it without the output command, it takes up only about 25% of the CPU. (when I run it with output command, it instantly gives an error, so doesn't really start running at all)

I had already tried adding -w (-w tig00000001:0-1334) (the length of the reference sequence), it runs the same, gives output in the Terminal window, however again when I add the output command (-o variants.vcf) to this, it again instantly gives the error Segmentation fault (core dumped). 

Am I maybe doing something wrong with the output command?

Thanks, 
Marrit

**Comment by jts** [comment] 2018-01-17 15:46
Hi,

Sorry for leaving this issue without a response. Could you send me fast5 files that will allow me to reproduce the problem?

Thanks,
Jared

**Comment by mh124** [comment] 2018-01-25 09:39
Hi Jared,

Thanks for your message, I can still really use the help, still haven’t been able to sort out the problem.
I have tried sending you the files I used (the fastq, the bam and the Canu draft assembly fasta file),  however I am unable to email it since it comes back to me with the message that the attachments are too large. (not sure if you also, or maybe only, need the fast5 files, but those are even bigger of course..). Not sure how I should send it to you? If you give an emailaddress I can send it to, then I can send them through wetransfer?

Thanks so much for the help,

Regards,
Marrit

**Comment by mh124** [comment] 2018-01-31 07:34
Hi Jared,

In the meantime I have managed to solve the issue, and to get the vcf file out. I think I made a mistake in the coding, because now it seems to work fine.

I still have a question though, the vcf file only contains SNP information. I was wondering if it is possible to get a fasta file out of it which contains the ambiquous bases. And if not, if you have any idea how I could achieve this when having the nanopolish consensus sequence and the vcf file with the SNPs. 

Thanks! 
Marrit

**Comment by jts** [comment] 2018-02-05 18:42
Hi Marrit,

Sorry but its not possible to output a consensus sequence with ambiguous bases at this time. It is something I hope to do in the future though. I'm going to close this issue for now, if you have other questions please feel free to open a new issue.

Jared

**Closed by jts** 2018-02-05 18:42 UTC
